### ISSUE TITLE
Support hi-resolution screens

### ISSUE THREAD

**Issue by dazld** [quil/quil#108]
I've had a look through the API, but I couldn't see a way to render the sketches in native resolution on hi-res screens (retina MBP, chromebook pixel etc). Is this possible?

**Comment by dazld** [comment]
I came back to quil after a while, and this doesn't seem to work any more, and I couldn't find an up to date example. Does this still work..?

**Comment by nbeloglazov** [comment]
Not sure. Looking at Processing docs they mention only support 3.0 which is still in alpha: https://github.com/processing/processing/wiki/Supported-Platforms#retina-support 
I don't know if older ways still work.
