### ISSUE TITLE
Bind *out* to output to REPL 

### ISSUE THREAD

**Issue by nbeloglazov** [quil/quil#115]
Currently all text printed by `println` and other print functions goes to stdout. It would be better if it went to REPL instead. Like here it is done here https://github.com/solita/inkwell#improved-support-for-interactive-programming-in-the-repl

**Comment by tangrammer** [comment]
Hi guys and specially @nbeloglazov !
I'm having problems with this issue, my repl doesn't refresh automatically, so until i dont press ENTER i dont get any result in my cider REPL. 

This is my cider config
```
;; Connected to nREPL server - nrepl://localhost:60551
;; CIDER 0.14.0snapshot (package: 20160830.23), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_31

``` 

and my project settings
```
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.8.51"]
                 [quil "2.4.0"]
                 [clj-time "0.12.0"]]

```

BTW: `println` always freezes my current nrepl ....
