### ISSUE TITLE
Any way for a quil (js) sketch to pause/unpause/restart?

### ISSUE THREAD

**Issue by doubleagent** [quil/quil#138]
Quil provides (\<host\>.core/\<host\>) for starting sketches, but does not provide a way to pause/unpause or restart a sketch (unless you want that logic inside the sketch).  Useful eg if you want to reflect state changes in an Om component.

Example is clojurology.com.  User clicks 'expand insights' and quil animates drawing the dowloads/version graph.  The animation can only occur once, instead of each time the button is clicked.

Unless it's feasible to destroy and reload the canvas object with the sketch.  I don't know how to do this.  Thoughts?

**Comment by nbeloglazov** [comment]
Closing this issue. Feel free to reopen if you still have problems.
