### ISSUE TITLE
`sketch` doesn't show anything

### ISSUE THREAD

**Issue by gcapizzi** [quil/quil#145]
I've created a project like this: 

```
lein new quil my-sketch
```

and then ran this in the REPL:

``` clojure
my-sketch.core=> (use 'quil.core)
nil
my-sketch.core=> (sketch :setup (fn [] (background 20) (ellipse 50 50 80 80)) :title "The moon delights the night")
#<Applet quil.Applet[panel0,0,0,500x300,layout=java.awt.FlowLayout]>
```

Everything seems to work properly but I don't see any window showing up :disappointed: Any idea?

**Comment by takosuke** [comment]
In my case, the sketches not only hide behind the window - they sometimes run away and hide at the very bottom of the window stack, behind everything else but the desktop!It doesn't always happen, I'm not sure when sorry
And when having exited an iterm2 fullscreen window, they appear as just tiny bars with the red/yellow/green buttons on top

**Comment by jaredly** [comment]
I'm also seeing this -- the quil sketch windows have no entry in the dock, and can't be `cmd-tab`'d to. But 4-swipe-up allows you to see & focus them. :/ this didn't always happen - a few days ago they appeared in the dock w/ a java icon.
quil v2.2.5, clojure 1.7.0, OSX Yosemite

**Comment by giuliano108** [comment]
I found an easy way to reproduce the problem.

- The Applet opens behind the other windows, doesn't show among the running MacOS apps, can't be `cmd-tab`'d to:

        $ boot repl -m cider.nrepl/cider-middleware
        boot.user=> (require 'sketch.core)

- Everything works as expected:

        $ boot repl
        boot.user=> (require 'sketch.core)

I'll do some more digging, but hopefully someone has an idea why `cider-middleware` is interfering?
