### ISSUE TITLE
examples don't run in repl or lighttable, but work fine when called directly with lein run

### ISSUE THREAD

**Issue by takosuke** [quil/quil#147]
Hello! I'm on osx 10.9.5 with clojure 1.6.0 and leiningen 2.5.0 on java 1.8.0_05 64 bit, latest lightbox (cant check what version that is right now will edit later)
I followed the tutorials in the examples page and in quil-workflow and the window shows up fine when i use lein run -m blablabla, but from lein repl i just get a nil and nothing happens, and same thing on lighttable. It's not the same issue mentioned elsewhere about the window being hidden, I triple checked :dancers: 
Im trying to set up emacs to try that next.

**Comment by nbeloglazov** [comment]
Closing this issue. Feel free to reopen if you still have problems.

**Comment by takosuke** [comment]
Sorry I didn't get back to you before - christmas, life and everything. 
Yes, it was probably the same as issue #145, plus my cluelesness about emacs/lighttable/nREPL
