### ISSUE TITLE
Creating multiple dragble and connectable elements

### ISSUE THREAD

**Issue by timur87** [quil/quil#150]
Hi, 

Could you please provide some tips for creating some elements which are dragable and connectable via other modeling elements? Is there a way to bind extra data to modeling elements, i.e., binding meta-data to circles, ellipses, etc.

Regards,

Timur

**Comment by nbeloglazov** [comment]
Hi Timur

Quil provides only primitives for drawing figures, it doesn't provide any modeling elements, you have to implement them yourselves. I usually represent elements as simple maps and implement functions that take this maps and draw object using Quil functions. This also allows easily extend my elements with additional data as they're simple maps and I can freely add new fields. 
If you want, you can provide your current code and I could try to help adding dragability to it.

Nikita

**Comment by timur87** [comment]
Hi Nikita,

Thanks for the answer, it helped. 

Regards,

Timur
