### ISSUE TITLE
Can quil handle math equations?

### ISSUE THREAD

**Issue by kindlychung** [quil/quil#151]
For example, process something like $\sum_{i=0}^k x_i^2$ and render it as in image.

**Comment by nbeloglazov** [comment]
Hi Kaiyin

Quil doesn't provide tools to render TeX equations. You can use [JLatexMath](http://forge.scilab.org/index.php/p/jlatexmath/) to render equations into png file. If you want to embed it into Quil sketch you can then simply render result png file using [load-image](http://quil.info/api/image/loading-and-displaying#load-image)/[image](http://quil.info/api/image/loading-and-displaying#image) combination. JLatexMath is present in maven so it is easy to include into leiningen project.

Nikita

**Comment by nbeloglazov** [comment]
Closing issue. Feel free to reopen if you have other question or ask in [google group](https://groups.google.com/forum/#!forum/clj-processing)

**Comment by kindlychung** [comment]
Cool, thanks!
