### ISSUE TITLE
Drawing rectangles with rounded corners

### ISSUE THREAD

**Issue by timur87** [quil/quil#152]
Hi,

How could I draw a rectangle with rounded corners? I saw stroke-cap function, however, it enables just a small rounding and I cannot set-up the degree of rounding. I want to draw something like this http://www-01.ibm.com/support/knowledgecenter/api/content/nl/de/SSNW2F_4.5.1/com.ibm.p8.doc/pe_help/designer/bpmn_task.gif

Regards,

Timur

**Comment by nbeloglazov** [comment]
Hi Timur

Take a look at [rect](http://quil.info/api/shape/2d-primitives#rect) method which takes 5 arguments. Last argument is corner radius. Also you can use google group [clj-processing](https://groups.google.com/forum/#!forum/clj-processing) for similar questions. It is usually used to discuss implementation questions.

Thanks,
Nikita

**Comment by timur87** [comment]
Hi Nikita,

Thanks for the hint again :)

I will ask my further questions in the mentioned google group. I was not
aware of it's existence.

Regards,

Timur
