### ISSUE TITLE
Working but with weird error at runtime.

### ISSUE THREAD

**Issue by dsiah** [quil/quil#153]
Hi I have the simple hello-quil example working however I recieve a bizarre error when I run the lein run command. I did add the :main as 

```   :main hello-quil.core ```

and I also added 

``` [quil "2.2.5" :exclusions [org.clojure/clojure] ] ``` 

because lein pulled down a bunch of different versions of clojure previously and recommended that add that exclusion.

```
$ lein run
Exception in thread "main" java.lang.Exception: Cannot find anything to run for: hello-quil.core, compiling:(/private/var/folders/r_/v1q42f254450q9lz8ty2zyc80000gn/T/form-init8517717259846406503.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Cannot find anything to run for: hello-quil.core
	at user$eval5.invoke(form-init8517717259846406503.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 11 more
```
Thanks

**Comment by nbeloglazov** [comment]
Hi David

Does youi file has -main function? If you specify :main option in
project.clj file the namespace must have -main function. Check this:
https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L196
Or more quil-specific instructions for building runnable jar:
https://github.com/quil/quil/wiki/Runnable-jar

Nikita

**Comment by dsiah** [comment]
haha that was silly -- I assumed that the -main function was generated in the example. It is almost working...

```
(q/defsketch hello-quil
  :title "You spin my circle right round"
  :size [1200 500]                      ; setup function called only once, during sketch initialization.
  :setup setup                          ; update-state is called on each iteration before draw-state.
  :update update-state
  :draw draw-state
                                        ; This sketch uses functional-mode middleware.
                                        ; Check quil wiki for more info about middlewares and particularly
                                        ; fun-mode.
  :middleware [m/fun-mode])

(defn -main
  [& args]
  (q/sketch
   :title "Example is working"
   :setup setup
   :draw draw-state
   :size [400 400]
   :features [:exit-on-close]))
```

The top code is what was supposed to be I assume the -main function since it is almost identical to what the tutorial you linked led me to produce -- the second function is of course mine. The problem with the second function is that the draw-state function takes a state which I cannot seem to figure out what to write in the second function. When I do not give it a state it crashes giving me an arity error (wrong number of args).

**Comment by nbeloglazov** [comment]
Quil provides 2 modes: 
1. Regular one, when you handle state changes by your own. In that mode `draw` function doesn't take any arguments and there is no `update` function.
2. fun-mode, which is [functional mode](https://github.com/quil/quil/wiki/Functional-mode-%28fun-mode%29). It is enabled by adding `fun-mod` middleware to list of middlewares when you create a sketch. In that mode `draw` has to take a `state` argument. And also you can provide `update` function which updates the state on each tick.

You have to be careful and have correct version of `draw` depending on which state you're using. In your case above you're creating 2 sketches at the same time (which is probably wrong, I think you need only the sketch in `-main`). You need to figure it which mode you want to use and then use correct mode in the sketch inside `-main`.

I think documentation is correct. Confusion comes from the fact that `lein new quil bla` generates a new quil project with default sketch which uses `fun-mode`, while "runnable jar" tutorial uses regular mode.

**Comment by dsiah** [comment]
perfect -- that clears it up, thank you.
