### ISSUE TITLE
Catch exceptions in with-translation

### ISSUE THREAD

**Issue by rbuchmann** [quil/quil#154]
Errors in a (with-translation ...) block mess up reloading for me, because the push-matrix calls will be executed, while the pop-matrix calls will not. Even when the problematic section is repaired, the sketch still won't run properly because additional calls to pop-matrix will cause exceptions. Could you put the pop-matrix call in a (finally ...) block?

**Comment by nbeloglazov** [comment]
Good point, thanks for the suggestion! I'll add it this week. Or you can do it, if you want. Should not be hard to do.

**Comment by nbeloglazov** [comment]
Thanks for fixing.
