### ISSUE TITLE
Live coding issues

### ISSUE THREAD

**Issue by AndreaCrotti** [quil/quil#159]
I'm not entirely sure this is even possible however, I'm having troubles trying to do some more interactive coding with Quil (using Emacs + Cider).
The code I'm using is very simple and stupid, now here:
https://github.com/AndreaCrotti/hangman/blob/master/src/hangman/quil.clj

And I have two issues really:
1. when there is an error in the draw function I don't get any stacktrace unless I call the draw directly from the cider repl
2. once the final image is rendered I can not do anything except for killing it and re-render again.

Are there ways to get around this?
I've seen the "inkwell" project which might help so I'll take a look, but any other hints?
thanks

**Comment by nbeloglazov** [comment]
Hi Andrea

1. Agree, it is quite confusing that in cider all exception stack doesn't go to repl buffer. Actually it goes to another buffer `*nrepl-server*`. I believe if you switch to that buffer you'll see the stacks. For debugging purposes you can use [pause-on-error](http://quil.info/api/middleware#pause-on-error) middleware. Actually it was inspired by the inkwell library your mentioned. There is an open issue for redirecting stack traces to repl buffer [#115](https://github.com/quil/quil/issues/115), but doing so hurts performance a little bit so I don't want to enable it by default. I'm thinking about adding it to the `pause-on-error` middleware.

2. Didn't understand the second question. Can you elaborate on the workflow you're thinking about? What should it draw and how do you want to interact with the sketch?

**Comment by AndreaCrotti** [comment]
1. @nbeloglazov ok thanks yes I'll check, the weird thing is that after a while it seems that all the output that should go to the Cider repl disappears (for example just doing a "println").
Can this be related still with quil or is something else? (I only noticed it in this project)

2. well I thought I could be able to add new shapes to an existing sketch, without having to redraw everything every time, but I'm not managing to do that so I think that maybe it's not possible?

**Comment by nbeloglazov** [comment]
1. Yes, it is still the same issue. Draw/update and other functions run in separate thread and output from that thread doesn't go to repl but to `*nrepl-server*`. 

2. Usually people clear the sketch on each frame and redraw everything. But if you want - you can clear sketch only when needed and each frame will be adding new shapes, thus avoiding needless redrawing. I did it for drawing trees recently: when I drew branches I didn't clear older branches so that at each point of time I had to draw only new branches, which drastically improved performance.

**Comment by nbeloglazov** [comment]
Closing this issue. @AndreaCrotti, if you have additional question feel free to reopen this issue or ask on [clj-processing](https://groups.google.com/forum/#!forum/clj-processing).
