### ISSUE TITLE
no-fill does not seem to work correctly with text and text-num in fun-mode.

### ISSUE THREAD

**Issue by Rorschach22** [quil/quil#161]
This first example draws both 500 and hello in white and doesn't draw the square.
```clojure
(defn draw-state [state]
    (q/background 0)
    (q/text-num 500 500 100)
    (q/text "hello" 500 200)
    (q/rect 80 80 80 80))
```

This next example draws both 500 and hello in white like the first example but no-fill is used. Still does not draw the square.

```clojure
(defn draw-state [state]
    (q/background 0)
    (q/no-fill)
    (q/text-num 500 100 100)
    (q/text "hello" 100 200)
    (q/rect 20 20 20 20))
```

This next example draws both 500 and hello using the fill color that was set before no-fill. Still does not draw the square.

```clojure
(defn draw-state [state]
    (q/background 0)
    (q/fill 80 255 80)
    (q/no-fill)
    (q/text-num 500 100 100)
    (q/text "hello" 100 200)
    (q/rect 20 20 20 20))
```

This final example draws both 500 and hello using the fill color. This also draws the square using the fill color.

```clojure
(defn draw-state [state]
    (q/background 0)
    (q/fill 80 255 80)
    (q/text-num 500 100 100)
    (q/text "hello" 100 200)
    (q/rect 20 20 20 20))
```

The reason we are wondering is because the quil api says text and text-num use the fill. If there is no fill. It seems to have an automatic white and if we set the fill to no-fill it takes whatever the last fill was. It would seem intuitive that using no-fill would not draw text and text-num. We are using fun-mode.

**Comment by nbeloglazov** [comment]
Seems like it is issue of processing itself: they don't check whether noFill is set when drawing text. Added the check in Quil. @Rorschach22, thanks for reporting!
