### ISSUE TITLE
How to call redraw from keyboard event

### ISSUE THREAD

**Issue by abelnation** [quil/quil#162]
I'm trying to figure out how to only do a redraw in response to a key or mouse event in functional mode using noloop.  The problem is that redraw does not take any state as a parameter, whereas the key/mouse events must return the new state.  

My question is, where should redraw be called?

**Comment by nbeloglazov** [comment]
Hi Abel. 
I think if you call `(redraw)` anywhere in listener - it should be fine. It should redraw sketch using new state after handler is finished. It works like this:
```clojure

(defn mouse-moved [state event]
   (redraw) ; mark sketch to be redrawn on next iteration
   (let [new-state ...]
      new-state))

; next iteration - 'redraw' flag is true
; redrawing sketch using new state and set flag back to false
```

**Comment by nbeloglazov** [comment]
Closing this issue. @abelnation i, if you have additional questions feel free to reopen this issue or ask on [clj-processing](https://groups.google.com/forum/#!forum/clj-processing).
