### ISSUE TITLE
smooth + opengl crashes hard on OS X

### ISSUE THREAD

**Issue by eigenhombre** [quil/quil#167]
The following minimal failing case crashes fairly reliably for me on OS X 10.10.5 with Java 1.8.0_60:

`project.clj`:

    (defproject moarquil "0.1.0-SNAPSHOT"
      :main moarquil.core
      :dependencies [[org.clojure/clojure "1.7.0"]
                     [quil "2.2.6"]])

`core.clj`:

    (ns moarquil.core
      (:gen-class)
      (:require [quil.core :refer :all]))

    (defn -main []
      (defsketch thisapp
        :setup (fn [] (smooth 8))
        :renderer :opengl))

This yields:

    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGSEGV (0xb) at pc=0x00007fff8c8b00dd, pid=56806, tid=1823
    #
    # JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
    # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
    # Problematic frame:
    # C  [libobjc.A.dylib+0x10dd]  objc_msgSend+0x1d
    #
    # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
    #
    # An error report file with more information is saved as:
    # /Users/jacobsen/Programming/Lisp/clojure/quilbug/hs_err_pid56806.log
    #
    # If you would like to submit a bug report, please visit:
    #   http://bugreport.java.com/bugreport/crash.jsp
    # The crash happened outside the Java Virtual Machine in native code.
    # See problematic frame for where to report the bug.

**Comment by nbeloglazov** [comment]
Could you try quil 2.3.0-SNAPSHOT which uses recently released Processing 3.0.1? 
https://clojars.org/quil/versions/2.3.0-SNAPSHOT

**Comment by eigenhombre** [comment]
That seemed to do the trick!!!
![screen shot 2015-11-03 at 7 35 25 am](https://cloud.githubusercontent.com/assets/382668/10909277/86fa1f76-81fd-11e5-8074-9cb886a0b144.png)

Thanks @nbeloglazov !

**Comment by nbeloglazov** [comment]
Hm, cool! I didn't really expect that it will fix it.

**Comment by eigenhombre** [comment]
@nbeloglazov You are right, apparently.  I missed this:

    >  lein run
    smooth() can only be used inside settings()

See also https://github.com/processing/processing-docs/issues/251

**Comment by nbeloglazov** [comment]
Argh, not cool. So processing 3 introduced new method `settings()` that should be used to set size and apparently smooth. I hoped I could keep it hidden in quil so API only has `:setup`. But I think I'll need to make `:settings` available as well only for smooth :( 
Reopening this issue.

**Comment by GoToLoop** [comment]
Don't forget **noLoop** either!  @_@

**Comment by nbeloglazov** [comment]
Thanks @GoToLoop. Added support for `:settings` just to support `smooth` and `no-smooth`. Feels ugly and I'm sure will be confusing for users, but couldn't think of a better way to support it. So usage is something like this;
```clojure
(q/defsketch my-sketh
  :settings #(q/smooth 2)
  :setup setup
  :draw draw)
```
Uploaded latest version to  https://clojars.org/quil/versions/2.3.0-SNAPSHOT

**Comment by nbeloglazov** [comment]
@eigenhombre could you try with 2.3.0 and putting smooth inside :settings?

**Comment by eigenhombre** [comment]
@nbeloglazov -- yeah, it works (and it's gorgeous).  Thanks! I don't have time to do a PR at the moment, but maybe we should update the README / docs before closing?

**Comment by nbeloglazov** [comment]
Update what exactly? I did update [smooth](http://quil.info/api/shape/attributes#smooth) and [no-smooth](http://quil.info/api/shape/attributes#no-smooth) docs to reflect the fact that they must be called inside :settings.

**Comment by eigenhombre** [comment]
@nbeloglazov see my PR -- seems like we're almost there.
