### ISSUE TITLE
pixel density for retina display 

### ISSUE THREAD

**Issue by shaunxcode** [quil/quil#169]
I could not find a wrapper in quil for: http://beta.processing.org/reference/pixelDensity_.html Which seems to be the way to set the pixel density so text does not look so washed out on a retina display. I tried the `(q/hint :enable-retina-pixels)` thing but it did not seem to have an effect? (Maybe I was not doing it in the right place? I tried in setup and settings?).

**Comment by nbeloglazov** [comment]
Right, I missed pixelDensity :( Didn't see it on Processing 2 => 3 changes pages and thought there were no new methods. I should take a closer look. Thanks for bringing that! Meanwhile as workaround you can try something like:  
```clojure
(q/defsketch ...
  :settings #(.pixelDensity (q/current-graphics) 2)
)
```
Basically using java interop to call .pixelDensity() directly. Note that it must done from :settings handler.

**Comment by shaunxcode** [comment]
Calling q/current-graphics inside of :settings handler yields nil for me?

**Comment by nbeloglazov** [comment]
Ah, right, graphics is not created yet at this point, but applet is (because settings() called before graphics object is created). Then `(.pixelDensity (quil.applet/current-applet))` might work. I'll try it tonight at home. And work on adding proper support of pixel-density.

**Comment by shaunxcode** [comment]
Yep, the following works in settings:

`#(.pixelDensity (quil.applet/current-applet) (.displayDensity (quil.applet/current-applet)))`

**Comment by nbeloglazov** [comment]
I also added logic that sets pixel density automatically: https://github.com/quil/quil/blob/master/src/clj/quil/applet.clj#L203. I think it should cover most cases so that users won't even need to be aware of `(pixel-density)` function. 

@shaunxcode what do you think? Can it be a problem?
