### ISSUE TITLE
determine if modifier key is pressed in conjunction with normal key

### ISSUE THREAD

**Issue by shaunxcode** [quil/quil#174]
I would like to be able to determine if a specific key is being typed in conjunction with a modifier e.g. alt/ctrl etc. Apparently in processing this can be done via calling .isAltDown and .isControlDown respectively on the event which they handler receives. I am not sure what the most idiomatic way to do implement this in the world of quil would be but it would be nice to have!

**Comment by GoToLoop** [comment]
AFAIK in Processing Java, each key combo generates a diff. [_key_](https://Processing.org/reference/key.html).
For example, CTRL+Z is `26`. Check it out further below:
https://forum.Processing.org/two/discussion/13928/reading-ctrl-z-in-keypressed

**Comment by nbeloglazov** [comment]
Agree, that would be quite useful. I'll think about how to implement it. In fun-mode it would be quite easy - all handlers get event object already so I can simply add some logic that adds few new keys to the events. As for standard, non-fun-mode, I'm not sure what the best way to do it. Meanwhile you can access event using `(.-keyEvent (quil.applet/current-applet))`. 

@GoToLoop yes, your approach is good but I think it works only for a set of special symbols such that CTRL+Z which have ASCII equivalent. Alt/shift + key don't have special meaning AFAIK.

**Comment by GoToLoop** [comment]
This is how I'd do it in "Java Mode":  :-D
```processing
// https://GitHub.com/quil/quil/issues/174
// GoToLoop (2015-Dec-14)

boolean isShiftDown, isCtrlDown, isAltDown;

void setup() {
  size(400, 300);
  smooth(4);
  noLoop();

  fill(#FFFF00);
  textSize(050);
  textAlign(CENTER, CENTER);
}

void draw() {
  String modifiers
    = "SHIFT: " + isShiftDown + ENTER
    + "CTRL:  " + isCtrlDown  + ENTER
    + "ALT:   " + isAltDown;

  background(#0000A0);
  text(modifiers, width>>1, height>>1);
}

void keyPressed() {
  setKeys(keyCode, true);
  redraw = true;
}

void keyReleased() {
  setKeys(keyCode, false);
  redraw = true;
}

void setKeys(int k, boolean bool) {
  if      (k == SHIFT)   isShiftDown = bool;
  else if (k == CONTROL) isCtrlDown  = bool;
  else if (k == ALT)     isAltDown   = bool;
}
```

**Comment by nbeloglazov** [comment]
I decided to go with `(q/key-modifiers)` functions that returns a set of currently active modifiers. Unfortunately I didn't find a way to get hold of event object in clojurescript so new function is available only in clojure.
