### ISSUE TITLE
Clojurescript: mouse-wheel propagates and scrolls page

### ISSUE THREAD

**Issue by NathanSmutz** [quil/quil#175]
I'm using the mouse-wheel to size objects in a Quil canvas (Clojurescript 1.7.170, Quil 2.3.0, fun-mode).
When scrolling the mouse-wheel, the canvas reacts whether or not the mouse is over the canvas and the page scrolls (undesired behavior) regardless of whether the mouse pointer is over the canvas. 
No such problem with right-click.
I'm seeing this behavior on Chrome 47.0.2526.106 (64-bit) and Firefox 43.0 so far (Linux Mint 17.3).

I've seen some solutions for mouse-wheel propagation in javascript: returning false from the event handler, invoking a .preventDefault() method on the event.

**Comment by nbeloglazov** [comment]
Yes, I had this problem as well a few times. Looking at processing.js code which is used by Quil - I don't think there is anything we can do at this point: https://github.com/processing-js/processing-js/blob/master/src/P5Functions/touchmouse.js#L302  

1. Processing registers mouse wheel event listener on document, not on canvas. 
2. Event object is not exposed in any way so we cannot call .preventDefaul() on it. 

I'll file a bug at processingjs repo about it.

**Comment by nbeloglazov** [comment]
Filed a bug on processing.js: https://github.com/processing-js/processing-js/issues/220

**Comment by NathanSmutz** [comment]
Good deal.  Looks like the Processing project owner is on-board.
