### ISSUE TITLE
Processing 3.0.2

### ISSUE THREAD

**Issue by BorisKourt** [quil/quil#177]
Hello,

Not sure if this is something that I can pull request, if I can, point me where. 

Processing 3.0.2 has been released with a [bunch of bug fixes](https://raw.githubusercontent.com/processing/processing/master/build/shared/revisions.txt) and it would be good to update `quil/processing-core` and friends to it. 

Thanks,
Boris

**Comment by nbeloglazov** [comment]
Thanks for the heads up. Yes, we should update quil to use latest processing. Unfortunately I don't think you can pull request as we need to [upload processing jars](https://github.com/quil/quil/wiki/Dev-notes#how-to-update-quil-when-new-version-of-processing-is-released) first and you don't have rights to push to quil repo in clojars. I'll try to do it tomorrow/this weekend.

**Comment by BorisKourt** [comment]
Ah alright.

Thanks for the details!
