### ISSUE TITLE
arc writes to current-applet instead of current-graphics

### ISSUE THREAD

**Issue by jackrusher** [quil/quil#179]
Hello, esteemed Quil maintainers. It looks like there's a bug in arc's implementation that prevents it from working with `current-graphics` (which I use constantly):

```
(.arc (ap/current-applet) (float x) (float y) (float width) (float height)
        (float start) (float stop)))
```

... it should be a super simple fix to switch this from `current-applet` to `current-graphics`.

Thanks in advance!

**Comment by nbeloglazov** [comment]
Thanks for reporting!

**Comment by jackrusher** [comment]
Thanks for the speedy fix. :)
