### ISSUE TITLE
Quil with Seesaw?

### ISSUE THREAD

**Issue by APOS80** [quil/quil#180]
Cant find a way to paint a canvas in Seesaw with Quil, is there a way or not?

**Comment by nbeloglazov** [comment]
I'm not sure it's possible. Processing `PApplet` class no longer extends awt Applet which means it's not a part of standard swing/awt framework that seesaw uses. Though if you use `:renderer :java2d` it created JFrame and Canvas elements under the hood and it is possible actually get them and add to your swing application created via seesaw, but it might be very fragile/hacky. I tried and couldn't make it work:

```clojure
(ns test.core
  (:require [quil.core :as q]
            [quil.middleware :as m]
            [seesaw.core :as c]))

(defn setup []
  (q/frame-rate 30)
  (q/color-mode :hsb)
  {:color 0
   :angle 0})

(defn update-state [state]
  (println "Dooing")
  {:color (mod (+ (:color state) 0.7) 255)
   :angle (+ (:angle state) 0.1)})

(defn draw-state [state]
  (q/background 240)
  (q/fill (:color state) 255 255)
  (let [angle (:angle state)
        x (* 150 (q/cos angle))
        y (* 150 (q/sin angle))]
    (q/with-translation [(/ (q/width) 2)
                         (/ (q/height) 2)]
      (q/ellipse x y 100 100))))

(defn create-sketch []
  (q/sketch
    :title "You spin my circle right round"
    :size [500 500]
    :setup setup
    :update update-state
    :draw draw-state
    :renderer :java2d
    :features [:keep-on-top]
    :middleware [m/fun-mode]))

(defn main [& args]
  (let [sketch (create-sketch)
        surface (.getSurface sketch)
        canvas (.getNative surface)
        proc-frame (.getParent canvas)]

    (c/invoke-later
     (.remove proc-frame canvas)
     (.setVisible surface false)
     (-> (c/frame :title "Hello",
                  :content (c/border-panel :center canvas)
                  )
         c/pack!
         c/show!))))

(main)
```

It throws error `Exception in thread "Animation Thread" java.lang.IllegalStateException: Buffers have not been created` :( But a similar question was asked on StackOverflow and seems like it should work: http://stackoverflow.com/questions/33101812/embed-processing-3-into-swing Maybe I'm doing something wrong.

**Comment by GoToLoop** [comment]
Class ***processing.awt.PSurfaceAWT.SmoothCanvas*** got a method called **getFrame()** which returns a ***JFrame*** instance being used by class ***processing.awt.PSurfaceAWT***:
https://forum.Processing.org/two/discussion/15398/limiting-window-resize-to-a-certain-minimum

**Comment by nbeloglazov** [comment]
Closing old issue. @APOS80, if you still have problems/need help - feel free to reopen. We can try make it work.

**Comment by Folcon** [comment]
So I've been trying to make this work, I've taken @GoToLoop's suggestion into account and I'm calling `.getFrame` instead of `.getParent`, but I'm still getting `java.lang.IllegalStateException: Buffers have not been created`.

However I'd much prefer to get a 3d context as well, so either `:p3d` or `:opengl`, not quite sure how to embed the GLWindow from processing into seesaw.

I've found [this](https://stackoverflow.com/a/28816844), which implies it should be possible? Though I could be reading that wrong.
