### ISSUE TITLE
inline image display

### ISSUE THREAD

**Issue by carocad** [quil/quil#181]
hey guys,
Although I have only used Quil once, I know that it has amazing capabilities which is why I'm reaching to you.

I recently created a [Lighttable plugin](https://github.com/carocad/nerdy-painter) to allow inline image displaying for Clojure. This was after I got frustrated of having so many windows floating around for some data exploration experiments.

The plugin basically takes any base64-encoded image an displays it inline. Both static (displayed as PNG) and dynamic (as SVG) images are allowed. I think it would be great to have Quil support for inline images in Lighttable.

Sadly I haven't found the way to hack into Quil to output the content as byte-array (enough to make it work) nor as base64. The closest thing that I have found is your image [save](http://quil.info/api/output/image#save) function. I could actually read the file and parse it to display inline but then it wouldn't be so dynamic.

In the README of my plugin there is a hack for Incanter. I guess that for Quil it should be something similar. Let me know your thoghts on this

**Comment by nbeloglazov** [comment]
Hi Camilo. You could try using [`pixels`](http://quil.info/api/image/pixels#pixels) function. It returns array of all pixels and you can convert it to base64 I assume. I think it will be close enough to byte-array.

**Comment by nbeloglazov** [comment]
Closing old issue. @carocad, if you still have problems with this - feel free to reopen it.
