### ISSUE TITLE
quil 2.4.0 has bug when use `{:optimizations :advanced}`

### ISSUE THREAD

**Issue by gfZeng** [quil/quil#182]
It's is seems quil 2.4.0 has a global `l` variable.

**Comment by nbeloglazov** [comment]
Hi Isaac. Can you provide more details? What error do you get? Is it compile or runtime error in browser console?

I tested quil with optimization :advanced as part of QA before cutting release. Also quil.info uses :advanced and it seems to be working fine.

**Comment by gfZeng** [comment]
It's run time error in browser. when I change back to quil 2.3.0, It's working.

It seems has an global `l = 0` variable.

**Comment by nbeloglazov** [comment]
What version of clojurescript are you using?

**Comment by gfZeng** [comment]
I tested at both version of ` [org.clojure/clojurescript      "1.7.228"]` and  ` [org.clojure/clojurescript      "1.8.40"]`, the same result --- working with `quil 2.3.0`, not working with `quil 2.4.0`

**Comment by nbeloglazov** [comment]
Is your project available on github so I can try it myself?

**Comment by gfZeng** [comment]
I also checked [quil.info js file](http://quil.info/js/main.js). There are also have a global variable `l` (search "for(l=")

This bug seems come from [processing-js](https://github.com/quil/processing-js/blob/master/resources/processing.js#L997) file

**Comment by nbeloglazov** [comment]
Indeed. Looks like processing folks forgot to declare `l`. Though I didn't see any problems when using it on chrome/firefox/safari. I still not sure what runtime error you're getting. I'd expect browsers just to declare global window.l variable and proceed with whatever they were doing. Does it interfere with some other global `l` variable? Hm. I assume clojurescript might generate a global function or something named `l`. Is that what are you seeing?

**Comment by nbeloglazov** [comment]
Can you try adding externs file that contains just:

```javascript
window.l;
```

I believe it should make closure compiler skip `l` variable. https://github.com/clojure/clojurescript/wiki/Dependencies#using-externs

**Comment by gfZeng** [comment]
Yeah, I use this way, currently.

**Comment by nbeloglazov** [comment]
Glad to hear you found a workaround. I'll update quil externs accordingly to ignore `l`.

**Comment by gfZeng** [comment]
IMO. the better way is fix processing.js

**Comment by nbeloglazov** [comment]
So there are multiple ways to do it.
1. Fix mistake in processing.js in their repo. Out of my control and probably not a critical issue for them.
2. Fix compiled processing.js in quil/processing-js. That means I have to remember to fix it every time I upload new version of processing.js
3. Add `window.l;` to externs. Might break if someone uses global `l` identifier on purpose (which I think is  unlikely). 

I think (1) is the ideal fix but I don't have much control here. And from (2) and (3) I prefer (3).

**Comment by gfZeng** [comment]
That right. I agree. 
Expecting the  version.
