### ISSUE TITLE
applet-close still in FAQ

### ISSUE THREAD

**Issue by houghcr** [quil/quil#183]
applet-close was removed in [https://github.com/quil/quil/commit/2c6ef9fb51cadd0cb69d57e531473b3b0ebf3d3b](https://github.com/quil/quil/commit/2c6ef9fb51cadd0cb69d57e531473b3b0ebf3d3b) but still appears in the FAQ on the wiki.

Also, how does one close the quil window from (clj) code currently?

**Comment by nbeloglazov** [comment]
Indeed. Looking at implementation of `q/exit`: https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L1656 it looks like 

```clj
(.exit my-sketch)
```
should do the trick. I'll try it and then update wiki.

**Comment by nbeloglazov** [comment]
`(.exit my-sketch)` works. Updated wiki. Thanks for reporting.
