### ISSUE TITLE
Reflections

### ISSUE THREAD

**Issue by blueberry** [quil/quil#185]
A lot of code in quil uses slow reflection calls, where simple type annotations would be a straightforward fix. Ditto for boxed math. Any plans to fix this? 

Here are some examples:
Reflection warning, quil/core.cljc:1675:3 - call to static method aset on clojure.lang.RT can't be resolved (argument types: unknown, int, java.lang.Boolean).
Reflection warning, quil/core.cljc:1747:17 - call to method displayDensity on processing.core.PApplet can't be resolved (no such method).
Reflection warning, quil/core.cljc:2181:19 - reference to field isAltDown on java.lang.Object can't be resolved.
Reflection warning, quil/core.cljc:2182:19 - reference to field isShiftDown on java.lang.Object can't be resolved.
Reflection warning, quil/core.cljc:2183:19 - reference to field isControlDown on java.lang.Object can't be resolved.
Reflection warning, quil/core.cljc:2184:19 - reference to field isMetaDown on java.lang.Object can't be resolved.
Reflection warning, quil/core.cljc:4084:16 - reference to field fill can't be resolved.

**Comment by nbeloglazov** [comment]
That sounds reasonable. I think I did such cleanup long time ago but probably new reflection calls were introduced since then. Would you be interested in doing?

**Comment by blueberry** [comment]
Sure. However, I only use clj, so I am not sure about the development and testing process.

**Comment by nbeloglazov** [comment]
That's fine. You can do it for clj and don't worry about cljs. Once you're ready - you can open pull request and I can test it for cljs. Or you can do it your self, see step 2 in release process: https://github.com/quil/quil/wiki/Dev-notes

All tests are manual as they involve looking at stuff and checking that it looks reasonable and couldn't think of a good way to automate it.

**Comment by blueberry** [comment]
I'll put that on my todo list. I won't be able to do it in the following days, but will hopefully get to it eventually.
