### ISSUE TITLE
Quil for ClojureScript — request to make `destroy-previous-sketch` part of the API

### ISSUE THREAD

**Issue by simon-katz** [quil/quil#186]
Hi.

I am beginning to learn Quil. So far it looks like a lot of fun, so many thanks for making it!

I want to use Quil from Reagent, and I have a `sketch` function that is like Quil's except that the `:host` argument is treated as the id of a canvas to create, rather than one that already exists.

In order for that to work nicely, I need to be able to destroy a sketch when it is unmounted. (If you are interested in the details, see https://github.com/simon-katz/nomisdraw/blob/for-quil-api-request/src/cljs/nomisdraw/utils/nomis_quil_on_reagent.cljs#L63 .)

So I would like `destroy-previous-sketch` to be part of Quil's API.

What do you think?

(This would be useful for any FRP-style approach, not only Reagent.)

Edit:
Improved code at https://github.com/simon-katz/nomisdraw/blob/create-random-canvas-id/src/cljs/nomisdraw/utils/nomis_quil_on_reagent.cljs

**Comment by nbeloglazov** [comment]
Hi Simon. I believe you can achieve the same effect with public API today. Can you try this:

```clojure
(q/with-sketch (q/get-sketch-by-id canvas-id)
  (q/exit))
```

**Comment by simon-katz** [comment]
Hi Nikita.

That works… sometimes. :-)

The `q/get-sketch-by-id` is unreliable, often returning nil. This seems to happen when I have had more than one sketch displayed and am trying to exit the second one (but only sometimes).

Some Googling suggested that other people had similar problems with Processing's `getInstanceById` (which is called by `q/get-sketch-by-id`).

I've worked around it by holding onto the sketch when I create it, so I can do:
```clojurescript
(q/with-sketch @saved-sketch-atom
  (q/exit))
```

If you are interested, my new code at and around https://github.com/simon-katz/nomisdraw/blob/5d21f77883ebacfc2a1c4d9d5da19141cce82fd0/src/cljs/nomisdraw/utils/nomis_quil_on_reagent.cljs#L72-L73

So I'm now only using the public API, which was my goal.

Thanks for your help.

**Comment by nbeloglazov** [comment]
Yes, keeping reference to actual sketch seems like a better solution than using `get-instance-by-id`. Glad to see that you made it work!
