### ISSUE TITLE
feature request: ``with-sketch`` in clojure.

### ISSUE THREAD

**Issue by magnetophon** [quil/quil#187]
I'm a total clojure newbie,but already love quil

Afaict there is no way of controlling sketch outside sketch code.
See [this](https://github.com/quil/quil/wiki/ClojureScript#with-sketch-macro).

I'd like to be able to have overtone events trigger drawing.

**Comment by nbeloglazov** [comment]
Actually, there is a way. You can use
```clojure
(quil.applet/with-applet my-sketch
  (ellipse 100 100 100 100))
```
It's kinda "internal" because it's not in quil.core but should work. And I guess it makes sense to make it public as `with-sketch`. Would you be interested in adding it?

**Comment by magnetophon** [comment]
@nbeloglazov
Thanks, I'll try that.
What do you mean by ''Would you be interested in adding it?''

**Comment by nbeloglazov** [comment]
I mean that `quil.applet/with-applet` is "private" I think it should be public by adding it to `quil.core/with-sketch`. This way `with-sketch` is going to work both in clojure and clojurescript.

**Comment by magnetophon** [comment]
@nbeloglazov Sounds good to me!

**Comment by nbeloglazov** [comment]
I tried to implement `with-sketch` for clojure but failed. Nothing was drawn on a sketch. I believe Processing doesn't support drawing outside of "draw" function. After `draw` is called processing [disposes graphics](https://github.com/processing/processing/blob/master/core%2Fsrc%2Fprocessing%2Fcore%2FPApplet.java#L2430) object and if we try to draw on it from another thread using `with-sketch` nothing will happen. It silently ignores all draw operations. 

Some other lifecycle functions like `start-loop` and `no-loop` might still work but it doesn't feel right to support `with-sketch` if only limited number of functions are going to work. I'm closing this issue as "not feasible". If anyone has ideas how to fix it - feel free to reopen.

**Comment by nbeloglazov** [comment]
So the only possible way from some other code (like overtone) to write something is to save data into an atom and have sketch `draw` function read this data and draw. There might be small lag between overtone updating atom and sketch drawing it, but given that FPS is pretty high 30-60, the lag should be hardly noticeable.

**Comment by magnetophon** [comment]
Thanks for looking in to it, and for providing a workaround.
