### ISSUE TITLE
adapting quil's create-graphics example to spit out a pdf generates a 0 byte pdf

### ISSUE THREAD

**Issue by PlagueInOslo** [quil/quil#189]
Not sure where I am doing something wrong, but I tried to change the example at 
[](https://github.com/quil/quil-examples/blob/master/src/quil_sketches/graphics.clj) to one where the image would be spitted out as pdf by changing line 42 from   

> (let [gr (create-graphics spiral-size spiral-size :java2d)]

to 
> (let [gr (create-graphics spiral-size spiral-size :pdf "filename.pdf")]

and changing line 48-49 
> (with-graphics gr (draw-spiral))

 to 

> (with-graphics gr (draw-spiral) (exit))

Not sure why it doesn't spit out a pdf. Maybe some trivial misunderstanding on my side.

**Comment by nbeloglazov** [comment]
Hi. Sorry for the late reply. I did some debugging and it's indeed impossible to do using only quil API, you'll have to use java interop. So the code will look like this:

```clojure
(let [gr (create-graphics spiral-size spiral-size :pdf "filename.pdf")]
  (with-graphics gr (draw-spiral))
  (.dipose gr))
```

Note the `(.dispose gr)` call at the end. This call closes pdf writer and flushes all content to file on disk. Actually I think there is a more idiomatic Processing way to do it using `beginRecord()` and `endRecord()` methods, but quil currently doesn't expose them. I'll add `do-record` macro:

```clojure
(do-record (create-graphics spiral-size spiral-size :pdf "filename.pdf")
  (draw-spiral))
```
