### ISSUE TITLE
Question : How can I access command-line arguments from within Quil?

### ISSUE THREAD

**Issue by interstar** [quil/quil#192]
Hi,

I want to access the command line arguments to a Quil program. Because I'm using the defsketch macro I don't have a traditional main function. Is there a way to get at command-line args in Quil?

**Comment by nbeloglazov** [comment]
Hi Phil. If you use main function I'd suggest using `sqetch` instead of `defsketch`. Check out [runnable jar](https://github.com/quil/quil/wiki/Runnable-jar) example. It uses exactly this technique and you can see that you easily use command line args during sketch initialization.

**Comment by interstar** [comment]
OK. Many thanks. 

(BTW : sorry to post questions here on GitHub ... wasn't sure if there was a better forum for that. Cheers.)

**Comment by Norgat** [comment]
Сall ```defsketch``` inside ```main``` function. I think it should work.
