### ISSUE TITLE
How to get vertices' coordinates after loading svg file by load-shape 

### ISSUE THREAD

**Issue by soulawaker** [quil/quil#193]
Hi, Nikita.

I am finding to get vertices' coordinates from svg file for regenertaing svg shape to quil's vertex shape.

In processing, there are some PShape methods like getVertex(), getVertexCount(), which I expect to use for my purpose.

But I can't find APIs corresponding to those methods.

Can I use those PShape methods in quil or an alternative to get coordinates from svg in quil?

**Comment by nbeloglazov** [comment]
Hi. Are you trying to use [load-shape](http://quil.info/api/shape/loading-and-displaying#load-shape) function? If so, it return an instance of PShape as you said and you can call java methods on it. It's true that quil doesn't have any special methods for that, but java interop is good enough:

```clojure
(let [shape (q/load-shape "shape.svg")]
  (println (.getVertex shape))
  (println (.getVertexCount shape)))
```

**Comment by soulawaker** [comment]
Thank you, Nikita. It worked!
