### ISSUE TITLE
Errors trying to use with-fill and with-stroke in quiljs

### ISSUE THREAD

**Issue by satchit8** [quil/quil#194]
In quiljs, was getting errors trying to use with-fill and with-stroke.
Specifically, errors that look like:

```
  Uncaught TypeError: quil.core.current_graphics.call(...).strokeColor is not a function(…)
```

and:

```
  Uncaught TypeError: quil.core.current_graphics.call(...).fillColor is not a function(…)
```

Changing the following lines: 

  https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L1267
  https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L1278

from:

```clojure
  (.fillColor (current-graphics))
```

and:

```clojure
  (.strokeColor (current-graphics)))
```

to:

```clojure
  (.-fillColor (current-graphics))
```

and:

```clojure
  (.-strokeColor (current-graphics)))
```

seems to work better here.

Are these appropriate changes?

**Comment by nbeloglazov** [comment]
Thanks for reporting and looking into it! Yes, suggested changes look reasonable but I think you need to keep `(.fillColor (current-graphics))` for regular clojure quil and add `(.-fillColor (current-graphics))` for clojurescript quil. Feel free to send a pull request.

**Comment by satchit8** [comment]
Thanks for taking a look.

AFAICT, the originally suggested form using instanceField form:

```clojure
  (.-fillColor (current-graphics))
```

works for both Clojure and ClojureScript in this case.  I ran some tests with slightly modified new projects for Clojure and ClojureScript with success.  It's possible I messed up though :)

Also the Java Interop docs at clojure.org say:


    The instanceField form is preferred for fields and required if both a field and a 
    0-argument method of the same name exist.

where IIUC instanceField form refers to:

``` clojure
 (.-instanceField instance)
```

At least in PGraphics.java, fillColor looks like a field to me:

``` java
  public int fillColor = 0xffFFFFFF;
```

I don't understand why for Clojure in this case, the instanceMember form:

``` clojure
  (.fillColor (current-graphics))
```

is preferred.  Though I think I undertand why it would work, as the Java Interop docs say:

    The instance member form works for both fields and methods.

Please help me understand.

**Comment by nbeloglazov** [comment]
Ah, thanks for the explanation!
