### ISSUE TITLE
Quil and self-host clojurescript

### ISSUE THREAD

**Issue by viebel** [quil/quil#195]
I'd like to be able to run quil code inside the browser using klipse (I'm the author of klipse) to allow people to write interactive graphics (and maybe games) in the browser where the reader could modify the quil code - like @jrheard did using plain js canvas here http://blog.jrheard.com/procedural-dungeon-generation-cellular-automata.

I tried to take a look at what you guys did in http://quil.info/sketches/create
But I need further help.

What is the best way for me to support quit inside klipse?

**Comment by nbeloglazov** [comment]
Hi Yehonathan 

Have you looked at https://github.com/quil/quil-site/blob/master/src/cljs/editor/quil_site/compiler.cljs? It does the compilation part. The setup in quil.info is following:

There is the main window and iframe where sketch runs. 
1. User clicks "compile".
2. We take user code and compile it in main window. Output of compilation is string with js code. Note that at this stage we compile only user code, we don't compile any of quil code. 
3. Compiled js code sent to the iframe with the sketch using postMessage.
4. Sketch iframe upon receiving postMessage evaluates js code. In the iframe we preload unobfuscated compiled quil + clojurescript core js so upon evaluating user code all quil and core functions are defined.

When we compile user code at step 2, it uses some quil and core macros and compiler has to be aware of them. To achieve that we preload compilation cache for quil and cljs macros namespaces: 
https://github.com/quil/quil-site/blob/master/src/cljs/editor/quil_site/compiler.cljs#L38
https://github.com/quil/quil-site/blob/master/src/cljs/editor/quil_site/compiler.cljs#L45

Cache is built beforehand by running cljs self-host on nodejs: 
https://github.com/quil/quil-site/blob/master/cache/src/cljs/cache/core.cljs

So, to support quil inside klipse I'd suggest doing similar: reuse caches to compile user code to js and evaluate it assuming that main quil library already preloaded.

**Comment by nbeloglazov** [comment]
Here is script that is preloaded in sketch iframe. All it does - it includes quil.core, quil.middleware so they're included by compiler and listens to postMessages and evaluates them. Pretty straightforward.
https://github.com/quil/quil-site/blob/master/src/cljs/preload/quil_site/preload.cljs

**Comment by nbeloglazov** [comment]
Closing this bug due to inactivity. If there are any questions still left - feel free to reopen.
