### ISSUE TITLE
mouse-pressed? issue with cljs

### ISSUE THREAD

**Issue by vsmart** [quil/quil#197]
hi @nbeloglazov, 

we're seeing an issue in our quil-cljs app. 
The mouse-pressed? function only returns nil. 

other mouse-relatd fns such as `mouse-x` work fine. 

do you have any pointers or ideas what the issue may be? 

thank you!

**Comment by Norgat** [comment]
Like this: https://github.com/processing-js/processing-js/issues/105 ?

**Comment by Norgat** [comment]
Quil-cljs is a wrapper around processing.js. I recommend check processing.js issue list for potential sources of this problem.

**Comment by vsmart** [comment]
thanks @Norgat! made it work by using the `:mouse-pressed` and `:mouse-released` properties in `defsketch` now. thanks for the pointer!

**Comment by nbeloglazov** [comment]
Franziska, thanks for reporting it. I believe there might be a real issue here. @Norgat, looking at quil implementation of `mouse-pressed?` we just return 'mousePressed' property of Processing object: [link](https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L2610). But according to the issue you referenced we should be using __mousePressed. I checked it and it seems to like __mousePressed indeed works:

http://quil.info/sketches/local/47f91e27fb59ceb0a99e71e5342cc033ba0e8639d8257513fb6363db81a50a15

**Comment by Norgat** [comment]
@nbeloglazov yes we can. But on every release of Processing.js we must check ```_mousePressed``` behaviour (because it's not a part of Processing API).

May be we can use your code as a manual test with simple changes:
```Clojure
(ns my.core
  (:require [quil.core :as q :include-macros true]
            [quil.middleware :as m]))

(defn setup []
  (q/frame-rate 30)
  (q/color-mode :hsb)
  {:color 0
   :angle 0})

(defn update-by-mouse [state]
  (let [{:keys [color angle]} state]
    {:color (mod (+ color 11.7) 255)
     :angle (mod (+ angle 1.1) q/TWO-PI)}))

(defn draw-state [state]
  (q/background 240)
  (q/fill (:color state) 255 255)
  (let [angle (:angle state)
        x (* 150 (q/cos angle))
        y (* 150 (q/sin angle))]
    (q/with-translation [(/ (q/width) 2)
                         (/ (q/height) 2)]
      (q/ellipse x y 100 100))))

(q/defsketch my
  :host "host"
  :size [500 500]
  :setup setup
  :draw draw-state
  :mouse-pressed update-by-mouse
  :middleware [m/fun-mode])
```

**Comment by nbeloglazov** [comment]
I'm ok with using non-public processing API. We can update our "automated" tests to verify that `mouse-pressed?` returns boolean. If it doesn't the test throws an error.

Maksim, I didn't fully understand your example. I don't see `mouse-pressed?` in it.

**Comment by Norgat** [comment]
@nbeloglazov huh, interesting. I thinking that ```mousePressed``` Processing event is what we need to call. I have miss that Processing.js have ```mousePressed``` event and ```mousePressed``` variable in Processing language **(!)**. So you're right - my code checks is not what we need.

But now I look at the Processing.js code and find one more potential bug in Quil cljs.
The list of Processing.js internal variables: https://github.com/processing-js/processing-js/blob/master/processing.js#L9796

1. ```__mousePressed``` (this discussion)
2. ```__keyPressed``` (missed now is Quil cljs)
3. ```__frameRate``` (currently used: https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L1871)


So, I think we need to change:

1. https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L2610
2. https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L2220

for cljs code like ```current-frame-rate```.

**Comment by Norgat** [comment]
@nbeloglazov 

> We can update our "automated" tests to verify that mouse-pressed? returns boolean. If it doesn't the test throws an error.

Hm, for Java version you write manual tests for events as I remember. What checks this test approach?

**Comment by Norgat** [comment]
I create pull request for this bug: https://github.com/quil/quil/pull/198
