### ISSUE TITLE
Missing random3D function

### ISSUE THREAD

**Issue by prakhar1989** [quil/quil#200]
Hi,

Thank you for this excellent library! I had a quick question - I see that the `random2d` and the `random3D` [functions](https://processing.org/reference/PVector_random3D_.html) are missing from this library. Sure, it's easy to generate a vector and then normalize it, but it would be convenient to not re-write that logic every time. Would love to hear your thoughts on this.

```clojure
(defn new-vector []
  (let [v (take 3 (repeatedly #(+ -0.1 (rand 0.2))))
        s (->> (map (fn [x] (* x x)) v)
               (reduce +)
               (Math/sqrt))]
    (mapv #(/ % s) v)))
```

**Comment by nbeloglazov** [comment]
Hi Prakhar. Having such funciton seems reasonable. I wouldn't use `PVector.random3D()` because it returns PVector and clojure has its own vector type. So clojure implementation of such function like you suggest is preferable. Though I'm wondering if there is a way to make it faster. I can imagine such function can be called often and should be optimized. Having multiple iterations like map/reduce/repeatedly might hurt performance. The optimized version won't be as idiomatic but I think it's a fair price to pay. Do you want to make a pull request?

**Comment by prakhar1989** [comment]
Hi @nbeloglazov,

Thanks for writing back! Having a more performant version of this completely makes sense and I would love to make a new PR. If you don't mind, can you give me ideas on how I can optimize the `map` and `reduce` portion of the above code?

**Comment by nbeloglazov** [comment]
Great! I was thinking the fact that vector has only 3 components. This allows us to generate each component separately as there are few them and not necessary to use iteration functions. We probably even use spherical coordinates to generate it: unit vector is essentially a point on a sphere with radius 1. And cartesian coordinatex x, y and z of point are determined using 2 angles and r: http://mathworld.wolfram.com/SphericalCoordinates.html Formulas 4, 5, 6

Given that r is 1. You just need generate 2 random angles and calculate x, y, z: 

```
theta = rand(0, 2PI)
phi = rand(-Pi/2, Pi2/)
x = cos(theta)*sin(phi)
y = sin(theta)*sin(phi)
z = cos(phi)
answer = [x, y, z]
```
It think it should be faster than generating 3 random coordinates and normalizing them. Also It should have more even distribution of random vector (see [this](http://stackoverflow.com/a/6283140/575421) stackoverflow answer).

**Comment by GoToLoop** [comment]
Dunno Closure. But perhaps you should be interested in the original **PVector::random3D()** implementation for Pjs:

```js
const TAU = 2 * Math.PI,
      pjsCheck = obj => obj != null && 'lerp' in obj;

function PVector(x, y, z) {
  this.x = x || 0, this.y = y || 0, this.z = z || 0;
}

PVector.fromAngle = (ang, t) =>
  t? t.set(Math.cos(ang), Math.sin(ang))
   : new PVector(Math.cos(ang), Math.sin(ang));

PVector.random2D = (t, p) => {
  const isPjs = pjsCheck(t), rnd = p? p : isPjs && t || Math;
  return PVector.fromAngle(TAU * rnd.random(), !isPjs && t || void 0);
};

PVector.random3D = (t, p) => {
  const isPjs = pjsCheck(t),
        rnd = p? p : isPjs && t || Math,
        ang = TAU * rnd.random(),
        vz  = 2*rnd.random() - 1,
        vzr = Math.sqrt(1 - vz*vz),
        vx  = vzr * Math.cos(ang),
        vy  = vzr * Math.sin(ang);
  return t && !isPjs? t.set(vx, vy, vz) : new PVector(vx, vy, vz);
};
```

**Comment by prakhar1989** [comment]
Thanks @nbeloglazov and @GoToLoop for the pointers! I'll raise a new PR shortly incorporating the changes you've suggested. Closing this for now.
