### ISSUE TITLE
quil with boot instead of lein?

### ISSUE THREAD

**Issue by jtoy** [quil/quil#204]
Im trying to use it with quil/Processing with boot instead of lein as it looks to make things simpler.
I wrote this simple script  and tried to run it, but all it does is launches a Java Applet window then immediately closes. There are no error logs for me to debug. is there something special to get it  running with boot?

    #!/usr/bin/env boot
    (set-env! :dependencies '[[quil "2.6.0"]])
    (require '[quil.core :as q])
    (defn setup []
      (q/background 111 111 111 )  )
    (defn -main  [& args]
      (q/defsketch my-art
      :size [800 800]
      :setup setup))

**Comment by nbeloglazov** [comment]
Not sure to be honest. Try adding `:draw` function. You can basically rename :setup to :draw. Also I suggest adding (println) to -main to make sure it runs. And add println to setup/draw.

**Comment by jtoy** [comment]
interesting. changing it to draw didn't help. but adding a sleep after calling defsketch does, this works for 5 seconds before shutting down:

`#!/usr/bin/env boot
(set-env! :dependencies '[[quil "2.6.0"]])
(require '[quil.core :as q])

(defn draw []
  (println "in draw")
  (q/background 111 111 111 )  )

(defn -main  [& args]
  (println "starting")
  (q/defsketch my-art
    :size [800 800]
    :draw draw)
  
(Thread/sleep 5000)

  )`

I thought that by using drawing, that should take over the program execution because it should be continuously called.  If I don't add the sleep ,the println inside of draw never gets called.   The println in main always gets called though.  There must be a more appropriate way to do this.

**Comment by jtoy** [comment]
FYI, on mac, adding sleep works, and on linux headless mode it works fine.

**Comment by nbeloglazov** [comment]
That's weird. I don't think I ever had problems when running using lein. Maybe it's specific to boot. One possible workaround is to block the main thread until sketch closes. Example:

```clojure
(defn -main  [& args]
  (println "starting")
  (let [sketch-finished (promise)]

    (q/defsketch my-art
      :size [800 800]
      :draw draw
      :on-close (fn [] (deliver sketch-finished true))

   (println "started sketch and wait for it to finish")

   ; derefing promise blocks thread until promise is fullfilled
   (deref promise)

   (println "sketch finished, exiting")))
```

**Comment by jedahan** [comment]
I've been playing with a very buggy template for quil + boot:

https://github.com/jedahan/ink 

Its my first time using any lisp, so it messy but I was able to get it kinda working.  Next is to have it hot-reload and work with both clj and cljs.... any suggestions are welcome

**Comment by dgtized** [comment]
With the recent release, there is some new documentation for using quil with the Clojure CLI tools. I get the impression that boot is mostly being phased out now that Clojure CLI exists, but perhaps I am mistaken. Happy to reference this work though if you are still interested in supporting boot?

**Comment by dgtized** [comment]
We are still in the process of improving support for Clojure CLI tools / deps.edn with the new release. As example we published a new deps-new template for CLJS projects under https://github.com/quil/sketchbook-template and a CLJ template is forthcoming. At this time I think the plan is to continue moving towards making Clojure CLI the default while still lightly supporting leiningen where possible. If there is ongoing interest in supporting boot, I'm happy to link to templates and documentation from the main docs, but I don't think we plan on actively developing support in that direction.

Closing this for now, feel free to re-open discussion if there is still active interest.
