### ISSUE TITLE
Reflection warnings

### ISSUE THREAD

**Issue by carcigenicate** [quil/quil#208]
When I run "lein check" on a project that uses Quil, I always get the following reflection messages:

```
Reflection warning, quil/middlewares/pause_on_error.clj:21:5 - reference to field beginDraw can't be resolved.
Reflection warning, quil/middlewares/pause_on_error.clj:21:5 - reference to field endDraw can't be resolved.
Reflection warning, quil/middlewares/navigation_3d.cljc:13:20 - call to java.lang.RuntimeException ctor can't be resolved.
Reflection warning, quil/middlewares/navigation_2d.cljc:13:20 - call to java.lang.RuntimeException ctor can't be resolved.
```

Could you resolve these please?

**Comment by nbeloglazov** [comment]
Thanks, @carcigenicate! Didn't know about `lein check`. Before that, I manually enabled `*warn-on-reflection*` and compiled quil.core so I missed all middleware. Added `lein check` to the release process [doc](https://github.com/quil/quil/wiki/Dev-notes)

**Comment by carcigenicate** [comment]
Awesome, thank you!
