### ISSUE TITLE
Asymmetry of key-pressed/key-pressed handler arguments. 

### ISSUE THREAD

**Issue by carcigenicate** [quil/quil#209]
Why (when in functional mode) does the key-pressed handler supply an event object, but key-released doesn't? It would be very helpful to have it passed in what key was released. 

Right now I'm using `q/raw-key` in the release-handler. Is this is idiomatic way?

**Comment by nbeloglazov** [comment]
Hi Brendon. Maybe it's a small bug. I thought that raw-key won't return anything in key-released because key was "released" and we no longer have it. But if it returns something then yes, we should pass event to the release handler.
