### ISSUE TITLE
How can i get quil-cljs to be able to resize the canvas?

### ISSUE THREAD

**Issue by 4nd1m4n** [quil/quil#212]
I already figured out, how to know the new width and height of the new canvas when a user has changed his browsers window size. Now i only need a way to update the size of my canvas.

I tryed to just overwrite the defsketch with a new one but that doesn't seem to work.

Can this be done? Or will i have to somehow use p5.js since it has a resize function available.

Many thanks for the great work so far.

**Comment by nbeloglazov** [comment]
Hi Andreas. 

Sorry for the late reply. Indeed, looks like resizing canvas element doesn't change internal width/height. But  it should be relatively easy to add to Quil. I'll do it. Thanks for reporting!

**Comment by NightMachinary** [comment]
@4nd1m4n Can you share your solution, please. :))
