### ISSUE TITLE
Can't get textures to appear.

### ISSUE THREAD

**Issue by 4nd1m4n** [quil/quil#213]
I want to have a shape of any kind to be drawn with a texture. But no matter how i try this, it just doesn't work. When i draw the image with the image draw function it works without a problem. In :p2d mode i get an error, that the texture object does not have a createTexture function. In :p3d i get an empty triangle without an error.

```
(q/texture-mode :normal)
(q/begin-shape :triangles)
(q/texture (:agario-lion @my-state))
(q/vertex 150 100 0 0.5 0)
(q/vertex 100 200 0 0   1)
(q/vertex 200 200 0 1   1)
(q/end-shape)
```

**Comment by nbeloglazov** [comment]
I made it work with P3D. Here is an example where we take this [image](https://github.com/quil/quil-site/blob/master/public/img/play.png) and reverse it: http://quil.info/sketches/show/-KoBCD2nlAgqIa_ivFQb

Not sure though how to make it work with P2D.

**Comment by nbeloglazov** [comment]
Another version: http://quil.info/sketches/show/-KoBEH8HSD62Hf9Ujuoq

**Comment by 4nd1m4n** [comment]
Hey, sorry for the long wait, but i was quite busy.
It strikes me how it is, that in the online editor you used it works just fine. But if i put your exact code in my project on my own computer with »lein cljsbuild auto« in a terminal, then it is compiled just fine, but i don't see anything on the canvas but rather have an error message.

Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.

So is my processing.js to old or something?

**Comment by nbeloglazov** [comment]
How are you opening html? Just from file manager or do you run static file
server, like "python -m SimpleHTTPServer" ? I think you have to do the
server so that page is opened using http:// protocol instead of file://

**Comment by GoToLoop** [comment]
Just a tip: all Firefox family browsers can run scripts under scheme `file://`. And always could!

**Comment by 4nd1m4n** [comment]
Ha! Thank you guys! Now it just works. With Firefox out of the box and with Chrome when i load it via http server.

I would have never figured that out that fast. :D

**Comment by GoToLoop** [comment]
@4nd1m4n, for a similar Firefox experience for Chrome-family browsers, there's a shortcut argument for it:
http://chrome-allow-file-access-from-file.com/
