### ISSUE TITLE
Recommended GUI Library setup

### ISSUE THREAD

**Issue by mefuru** [quil/quil#215]
Hi,

I have been looking for a library like [controlP5](http://www.sojamo.de/libraries/controlP5/) to implement in my Quil sketches, to enable users to change the values of parameters via sliders, knobs, buttons etc. Does anyone have a GUI library setup they could share?

Thanks

**Comment by nbeloglazov** [comment]
Hi Mehul. Try asking https://groups.google.com/forum/?fromgroups#!forum/clj-processing You reach more quil users there.

**Comment by mefuru** [comment]
Thanks Nikita, I'll ask there.
