### ISSUE TITLE
error in process filter: [nREPL] No response handler with id nil found

### ISSUE THREAD

**Issue by heyarne** [quil/quil#217]
I'm trying to develop sketches using Emacs; when printing something from within a function I get the above mentioned error: `error in process filter: [nREPL] No response handler with id nil found`

``` clojure
(defn mouse-pressed
  [& args]
  (println "Mouse pressed args:" args))

(q/defsketch blue-growth
  :title "Particle growth system"
  :size [720 720]
  :setup setup
  :update update-state
  :mouse-pressed mouse-pressed
  :draw draw-state
  :features [:keep-on-top]
  :middleware [m/fun-mode])
```

I can run the whole buffer and interact with it using CIDER, however printing does not work - it would help me greatly exploring the API. Any idea what's going on?

Versions:
* emacs 25.2
* CIDER 0.15.0snapshot (package: 20170630.2342), nREPL 0.2.12
* Clojure 1.8.0, Java 1.8.0_131

**Comment by nbeloglazov** [comment]
I believe printing works, but in prints to some other buffer by default. If you çheck all cider-related buffers in emacs you should see the message. Also there is a middleware that redirects all printlns to expected buffer. Here it is: https://github.com/quil/quil/blob/master/src/clj/quil/middlewares/bind_output.clj#L4 Try using it as `:middleware [quil.middlewares.bind-output/bind-output m/fun-mode]`. It should work (at least it worked when I created it originally) but no guarantees.

**Comment by heyarne** [comment]
I just realized my problem came from a slightly different angle; I had an erroneous call in `draw-state`, where I was calling the fill function like `(q/fill [0 255 255])`. The vector argument is wrong of course, but I didn't realize it at the time - so I guess stderr is not redirected at times? Thanks for the hint about the middleware though.

I tried adding the original `*err*` binding to the middleware to make it more robust but failed unfortunately. Any idea why that is? Thanks so much for the great library by the way, I'm enjoying it a lot!

**Comment by nbeloglazov** [comment]
You can try [pause-on-error](http://quil.info/api/middleware#pause-on-error) middleware which pauses sketch and prints error on sketch screen. As for seeing error in cider, I don't remember for sure. It should be in one of emacs buffers.
