### ISSUE TITLE
How to use q/pixels?

### ISSUE THREAD

**Issue by elect000** [quil/quil#219]
Now, I'd like to draw a picture on a cell-by-cell basis. So I used #'q/pixels , but I cannot I could not color a canvas in ''http://quil.info/sketches/local/ ...'' 
How do I add a color on a cell-by-cell? Thank you.
```
(ns test.core
  (:require [quil.core :as q]
            [quil.middleware :as m]))

(def width 100)
(def height 50)

(defn setup []
  (q/frame-rate 20)
  (q/background 200))

(defn draw []
  (q/background 200 30 40)
  (q/pixels
   (for [i (range width) j (range width)]
     (q/color 0 20 200))))

(defn update-state []
  (q/update-pixels
   (for [i (range width) j (range width)]
     (q/color 2 20 200))))

(q/defsketch test
  :title "yellow"
  :settings #(q/smooth 2)
  :setup setup
  :update update-state
  :draw draw
  :size [width height])
```

**Comment by mefuru** [comment]
Hi, to add colour cell by cell, you'd need to use the (q/set-pixel) function, rather than (q/pixel) and to set the fill colour, use the (q/fill) function rather than (q/colour).

**Comment by nbeloglazov** [comment]
Also here is an example: https://github.com/quil/quil/blob/master/test/cljs/quil/manual.cljs#L132

**Comment by elect000** [comment]
Thanks for your Teaching!!!

![2017-10-25](https://user-images.githubusercontent.com/18697629/31982213-87643054-b992-11e7-8e52-883e2485f5b8.png)
