### ISSUE TITLE
cljs pixel-density and display-density

### ISSUE THREAD

**Issue by shaunlebron** [quil/quil#221]
quil sketches look blurry on retina screens.  setting `pixelDensity` to the `displayDensity` is the solution, but they are strangely absent from processing.js API, which explains why they are missing from quil:
http://processingjs.org/reference/

I couldn't find any relevant discussion on this, but it seems simple to retrofit:

- `displayDensity()`
  - get from [`devicePixelRatio`](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio)
- `pixelDensity()`
  - set style.width = width (same for height)
  - set canvas.width = width*density (same for height)
  - set mouseX = mouseX * density (same for Y)
  - scale drawing coords by density

Is this something you're interested in having patched?

**Comment by nbeloglazov** [comment]
Hi Shaun. Yes, that would be great to patch. Would `pixelDensity()` set window.devicePixelRatio to a different value as well?

**Comment by shaunlebron** [comment]
Oops, the MDN example was actually wrong— canvas certainly does not auto-scale by looking at `devicePixelRatio`.  That's manual work that you have to do yourself.  I double-checked with the spec, and went ahead and just fixed the MDN example and removed the error from the description.

So, as far as quil goes, `pixelDensity()` should just keep the given value as internal state and use it for setting the canvas `style` size and scaling the coordinate system for both drawing and mouse events.

I'll look at how to do this for Quil, but feel free to take if the new MDN example clears it up enough.  It seems straightforward, but I'll need to spend a little time learning what Quil is doing.

**Comment by shaunlebron** [comment]
actually, I think it makes more sense to add this to processing.js first.  I'll create the issue and link here.

**Comment by heyarne** [comment]
Is there any update on this? What's the suggested approach for retina-compatible quil-cljs sketches?

**Comment by nbeloglazov** [comment]
Processing.js calls user-provided `setup` function. In the case of quil here is the `setup` function we pass: https://github.com/quil/quil/blob/master/src/cljs/quil/sketch.cljs#L112 Are you saying that we just need to move size setting to execute after lines 116 and 117?

**Comment by shaunlebron** [comment]
Oh cool, so we just need to defer what happens in the size function to
execute after setup is called, since we have to use the pixel density to
influence the size

**Comment by nbeloglazov** [comment]
Shaun, do you want to try it? I don't have mac with retina (need to ask friends) so can't easily test it. There is a section in quil readme which tells how to easily run test sketch from sources: https://github.com/quil/quil#developing.

**Comment by shaunlebron** [comment]
a reviewer on the processing.js team was receptive to merging the fix there, so I think that's where it should happen.

i'd prefer to defer to someone else, but i may try it later in the week

**Comment by anthonygalea** [comment]
As of quil 3.0.0 [display-density](http://quil.info/api/environment#display-density) and [pixel-density](http://quil.info/api/environment#pixel-density) are supported. Migrated from processing.js to p5js. See https://github.com/quil/quil/issues/255 for more details.
