### ISSUE TITLE
Jagged edge when drawing arcs in quil.js

### ISSUE THREAD

**Issue by glorphindale** [quil/quil#229]
Raised in an [SO question](https://stackoverflow.com/questions/48207021/arc-stroke-smoothness).

Using the following code produces an arc with a jagged edge in quil.js (q/smooth has no effect):
```
(defn draw-state [state]
  (q/background 150)

  (q/stroke-weight 14)
  (q/no-fill)
  (q/stroke 255 255 255)
  (q/arc 200 200 140 140 0 40))
```

Does not happen in quil on the JVM, does not happen in Processing.js.

**Comment by nbeloglazov** [comment]
Hi. Thankk you for reporting the bug. Do you have an example of processing.js code where the problem doesn't appear? I tried translating clojure code to Processing.js and still get jagged edges.

**Comment by glorphindale** [comment]
Tried on the sketchpad.cc:
```
void setup() {
    background(150);
    size(300, 300); 
    frameRate(5);
    strokeWeight(14);
} 
void draw() {
    noFill();
    stroke(255, 255, 255);   
    arc(200, 200, 140, 140, 0, 4);
}
```
There is some jaggedness, but not as much as in the SO question.

**Comment by nbeloglazov** [comment]
Here is what I get with your code on processing.js: https://drive.google.com/file/d/1ZeDx5MrawBCRDVtKx7oVzmrcSwYI6xIT/view?usp=sharing 

I checked all functions used in sketch and quil just translates them to processing.js versions, without doing anything extra. So I think it's processing.js issue. Also found this issue related to arc being not precise enough: https://github.com/processing-js/processing-js/issues/187

**Comment by glorphindale** [comment]
I've tested via sketchpad.cc on Windows 7 with Chrome 63 and Firefox 45 ( [see this screenshot](https://imgur.com/a/Oz0Cj) ) and it differs greatly from your result. What could possibly give such a stark difference?

**Comment by nbeloglazov** [comment]
Thanks, I didn't realize sketchpad.cc is a website :) Ok, so here is what I got. Arc looks great on sketchpad.cc. sketchpad.cc uses processing.js 1.4.8. Quil uses processing.js 1.6.6. Arc got broken between 1.4.8 and 1.6.6. After checking each version I found that it got broken in 1.4.16. There were multiple commits related to `arc` in 1.4.16: [one](https://github.com/processing-js/processing-js/commit/105ec5fbc819fab4c7ce578acc08e45c9604060f), [two](https://github.com/processing-js/processing-js/pull/186). They accidentally (or intentionally?) made arc drawing worse when a thick line is used.

I'm not going to roll back quil to use processing.js 1.4.8. It would be great if someone fixed arc in processing.js. I know that processing.js in support mode so chances of it being fixed are not high. I might take a shot at some point if I feel adventurous and math-hungry.

**Comment by GoToLoop** [comment]
AFAIK, even though Pjs repo got 1 oversëer there (@Pomax), he usually replies reasonably fast.

**Comment by nbeloglazov** [comment]
I would be really happy if this bug was fixed, but I remember Mike mentioning on other processing.js bugs that processing.js is in maintenance mode so I don't know if we should expect fix soon.

**Comment by anthonygalea** [comment]
After [migration](https://github.com/quil/quil/issues/255) from processing.js to p5js in quil 3.0.0 there are no jagged edges with [arc](http://quil.info/api/shape/2d-primitives#arc):

<img width="900" alt="Screenshot" src="https://user-images.githubusercontent.com/1301852/55681307-2d4a0b00-5925-11e9-81b9-95a692b10dfb.png">

**Comment by ampersanda** [comment]
Gonna close this thread on stackoverflow, after I tried it :D

**Comment by Pomax** [comment]
Also, processing.js is now an archived project
