### ISSUE TITLE
pop-style doesn't popping the style

### ISSUE THREAD

**Issue by ampersanda** [quil/quil#230]
I am trying to create a clock where my post before is on [stackoverflow](https://stackoverflow.com/questions/48207021/arc-stroke-smoothness). I have done with the process of making the clock, but I have an issue about the `(quil/pop-style)` which seems doesn't work with `JVM` (correct me if I'm wrong), but works on `web` which make the clock rotation false.

This is the screenshot of it, (left for web and right for JVM)
[https://i.stack.imgur.com/MP3hD.png](https://i.stack.imgur.com/MP3hD.png) 

Thank you, love Quil so much

**Comment by nbeloglazov** [comment]
Hi Mochamand. pop-style seem to be working for me. Here is an example: http://quil.info/sketches/show/-L2x7D3uiDsEGsvNvNbU I tried it both in clojure and clojurescript and in both cases I saw 2 red and 1 green circles. Do you have a specific example of a sketch where pop-style doesn't work?

**Comment by ampersanda** [comment]
It works on `quil-cljs` but not in `quil`

**Comment by nbeloglazov** [comment]
Which example? The one that I provided [here](http://quil.info/sketches/show/-L2x7D3uiDsEGsvNvNbU)? When I run it locally on quil (JVM, clojure) I see 2 red circles and 1 green. Do you see 1 red and 2 green?

**Comment by ampersanda** [comment]
I think I am wrong which is error on my code, I made a simple clock but the screenshot at the bottom of my post doesn't get the same result of rotation. please follow [this link](https://stackoverflow.com/questions/48207021/arc-stroke-smoothness)

**Comment by nbeloglazov** [comment]
I checked your example and I think I know what's the problem. You are using push-style/pop-style to "save" rotation state. But push/pop-style work with styles (like color or stroke weight). For things like rotation/translation/scaling you should use push-matrix and pop-matrix. Or even better you can use [with-rotation](http://quil.info/api/transform/utility-macros#with-rotation) macro. Example:

```clojure
(let [angle (* q/TWO-PI h)]
  (q/stroke 255 100 150)
  (q/arc 0 0 300 300 0 angle)
  (q/with-rotation [angle]
    (q/line 0 0 60 0)))

(let [angle (* q/TWO-PI m)]
  (q/stroke 150 100 255)
  (q/arc 0 0 280 280 0 angle)

  (q/with-rotation [angle]
    (q/line 0 0 70 0)))

(let [angle (* q/TWO-PI s)]
  (q/stroke 150 255 100)
  (q/arc 0 0 260 260 0 angle)

  (q/with-rotation [angle]
    (q/line 0 0 128 0)))
```

**Comment by ampersanda** [comment]
Ohh.. My bad, Thank you for the solution, but it's strange that the rotation works perfectly on `quil-cljs`

**Comment by nbeloglazov** [comment]
Yes, I agree. They should be consistent ideally, though it's up to underlying processing and processing.js to be consistent. Anyway, glad that I was able to help. Closing this bug.
