### ISSUE TITLE
save and save-frame open blank tab in chrome

### ISSUE THREAD

**Issue by raffomania** [quil/quil#233]
In chrome 63, calling `save` or `save-frame` just opens a blank tab instead of my image. In firefox, everything works as expected.

**Comment by nbeloglazov** [comment]
Thanks for reporting! Seems to be related to https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM%5B76-100%5D Might need to fix it in processingjs first. I'll poke around and see if can come up with a fix. Here is one possible thing to try out: https://github.com/niklasvh/html2canvas/issues/1271

**Comment by guidoschmidt** [comment]
Hey I just stumbled upon this, too. I did a custom fix using an `a` element with the `download` attribute and triggering a click event programatically: https://github.com/guidoschmidt/sketchbook/blob/master/cljs/src/sketchbook/utils/download.cljs

**Comment by nbeloglazov** [comment]
Thanks for nice example Guido. I'll take a look at this issue after we migrated to p5js. If we have problems with using p5js functions - I'll use your approach.

**Comment by anthonygalea** [comment]
Hi Rafael, just [tested save](http://quil.info/sketches/show/snippet_save) in chrome with quil 3.0.0 after [migration to p5js](https://github.com/quil/quil/issues/255) and I don't see this issue anymore.
