### ISSUE TITLE
quil.info unavailable

### ISSUE THREAD

**Issue by twitchett** [quil/quil#234]
Thanks for this great library.

I noticed the docs site referenced in the README, [quil.info](http://quil.info), is returning a 404.

Would be great to bring it back to life if possible, or remove the links to it if not.

**Comment by nbeloglazov** [comment]
Oops, thanks for notifying! Restarted the website. Should be available now. Embarrassingly I didn't have any alerts set up. So I created some so next time I should be notified by email if the site goes down.

**Comment by twitchett** [comment]
Fantastic!
