### ISSUE TITLE
ExceptionInitializerError

### ISSUE THREAD

**Issue by SOberhoff** [quil/quil#235]
I just tried running quil for the first time. Upon loading a namespace that required quil I got 

```
CompilerException java.lang.ExceptionInInitializerError, compiling:(quil/core.cljc:1:1) 

java.lang.ExceptionInInitializerError, compiling:(quil/core.cljc:1:1)
	...
Caused by: java.lang.ExceptionInInitializerError
	...
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at processing.core.PApplet.<clinit>(PApplet.java:119)
	... 92 more
```

I'm running both Clojure and Java 1.9.

**Comment by nbeloglazov** [comment]
Hi. Thanks for reporting. Unfortunately, it's a known issue. Quil doesn't work on java 1.9 because of Processing. We are tracking it here: https://github.com/quil/quil/issues/228 I'll close this issue as duplicate. For know all I can suggest is to use java 1.8.

**Comment by nbeloglazov** [comment]
Actually new version of Processing was released a few days ago. I'll try it and see if it works on java 9.
