### ISSUE TITLE
Sketch ignores the title key

### ISSUE THREAD

**Issue by mishadoff** [quil/quil#236]
Quil sketches ignores the title key and always show the title name as "Applet". Looks like it ignored in `prepare-applet-surface` at `quil.applet`

**Comment by nbeloglazov** [comment]
Thanks for reporting Misha! Wow, indeed param is unused. If only we had some kind of linter to catch such errors. Do you want to take a stub at fixing given that you already looked into it?

**Comment by astoeckley** [comment]
This is strange; I came across the same problem. However, many Quil screenshots including on the front page with the Circles demo (title says "Oh so many grey circles") show a custom title in the window. I assume this worked at one point but does not any more?

**Comment by nbeloglazov** [comment]
Answering @stoeckley questions (better late than never, right?...)

Handling of title got broken a while ago, probably in this commit: https://github.com/quil/quil/commit/aa98df1ec46b12024a3d6065ba909df6b4f77bd5. 

As for applets. Yes, you are right, Processing no longer users java applets, but they still call the main class `PApplet`. And Quil doesn't use use "Applet" in title. The default name of a sketch is "Quil 1": [code](https://github.com/quil/quil/blob/master/src/clj/quil/applet.clj#L299). At least that's what I'm getting now when running random sketch after @mishadoff fixed title handling.
