### ISSUE TITLE
Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central

### ISSUE THREAD

**Issue by cjsauer** [quil/quil#247]
Currently getting this error on a completely fresh project with only clojure and quil specified in `deps.edn`:

```
Error building classpath. Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
```

Here is my deps.edn file:

```
{:deps
 {org.clojure/clojure {:mvn/version "1.9.0"}
  quil                {:mvn/version "2.7.1"}}}
```

I believe the offending dependency is [com.lowagie/itext][1], which looks like it depends on bouncycastle. Any ideas? Thanks.

EDIT: It appears that the above library is [potentially deprecated][2]

[1]: https://mvnrepository.com/artifact/com.lowagie/itext/2.1.7
[2]: http://www.lowagie.com/iText/

**Comment by jorinvo** [comment]
Also ran into this. Saw that other projects had the same issue: https://github.com/incanter/incanter/issues/388

Thanks for the workaround @cjsauer :)

**Comment by transducer** [comment]
Same error and solution for Clojush

```
clojush {:mvn/version "3.17.1" :exclusions [com.lowagie/itext]}
```

**Comment by anthonygalea** [comment]
I believe #276 fixed this issue. Can it be closed or is it still open for some reason?
