### ISSUE TITLE
Not compatible with Java 11

### ISSUE THREAD

**Issue by mjg123** [quil/quil#250]
Not sure if this is related to the Java 9 issues already raised (but I'd suggest closing them anyway as JDK9 isn't supported any more).  11 is a LTS release and is likely to be more widely adopted than 9 or 10 were.  The error is:

```
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(quil/core.cljc:1:1)
---8<---SNIP----8<----
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
---8<---SNIP----8<----
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at processing.core.PApplet.<clinit>(PApplet.java:120)
        ... 105 more
```

I haven't dug into it yet but it's easy to repro with `lein new quil hello-quil` then `lein run` on JDK11.

**Comment by mjg123** [comment]
To be fair, it looks like the exception is coming from Processing's bootstrap, and they say:

> At the moment, it's likely not even possible to use Processing with Java 9 or later, due to several internal changes that break Processing libraries or the PDE itself.
>
> Unfortunately, Oracle's Java Road Map is a complete mess for a project like ours. Java 9 will already be unsupported as of March 2018, and Java 10 will be unsupported just six months later in September 2018. As a result, there are no plans to support Java 9 or 10. The first version we might use is Java 11, a "long term support" release, scheduled for September 2018. However, without anyone contributing their time to rework the code for Java 9/10/11, we'll be using Java 8 for the foreseeable future.

**Comment by nbeloglazov** [comment]
Matthew, by exit earlier you mean print an error like "java 11 is not supported yet"?

**Comment by nbeloglazov** [comment]
Also I'm not sure I can check it before PApplet class is initialized. Given that Processing checks java version in static field we need to add our check before java initializes PApplet class which I'm not sure how to do.

**Comment by sidec** [comment]
there is PR in main processing repo that migrates project to the latest Java LTS (11). 
[here](https://github.com/processing/processing/pull/5753)
It seems to be ready for merge but I am not sure how long it will to take to reach the release, PR is open since January. I am running this branch on Ubuntu 18.04 with no issues.
@nbeloglazov I can't find in this repo anything that packages `quil/processing-*` artifacts. Do you store some scripts somewhere on the internet? I can't see anything related to that in processing github as well. I am thiniking of packaging branch supporting Java 11 for local development  and to test how it goes with latest `quil`

**Comment by nbeloglazov** [comment]
@sidec I do it manually. Here are the instructions: https://github.com/quil/quil/wiki/Dev-notes#how-to-update-quil-when-new-version-of-processing-is-released If you could check whether it works with quil - it'd be great. Though for actual support we'd need to wait for new processing version once this PR lands.

**Comment by sidec** [comment]
Thanks @nbeloglazov! this is what I need. I will keep you updated

**Comment by dgtized** [comment]
Closing as [Quil v4.3.1323](https://github.com/quil/quil/releases/tag/v4.3.1323) has been released. It tracks the [Processing 4.3](https://github.com/benfry/processing4/releases/tag/processing-1293-4.3) and p5js 1.7.0 releases for aarch64, amd64, and MacOS Universal (intel/M1)  architectures on Java 17+.
