### ISSUE TITLE
In documentation, better differentiate fill, fill-int, and fill-float

### ISSUE THREAD

**Issue by zck** [quil/quil#252]
These three functions are all obviously related, but the [documentation](http://quil.info/api/color/setting#fill) doesn't explain the difference well. For reference, the three docstrings:

### fill
> Sets the color used to fill shapes.

### fill-float
> Sets the color used to fill shapes. For example, (fill 204 102 0), will specify that all subsequent shapes will be filled with orange.

### fill-int
>  Sets the color used to fill shapes.

Especially confusing is that `fill` and `fill-int` have the same docstring. Also, `fill-float`'s example doesn't use floats. So this leaves me at at a bit of a loss as to when to pick which function. [The code](https://github.com/quil/quil/blob/18bb527e1879f9d93507449aa6e1a40c4a523328/src/cljc/quil/core.cljc#L1696) shows that `fill` delegates to the other two. And, if given only a single argument, `fill-float` takes that as `grey`, but `fill` and `fill-int` take it as `rgb`.

Perhaps part of my confusion is that I did not learn Processing before Quil, so I have been relying on Quil's documentation to teach concepts, and not Processing's.

Sorry if this is a bit of a braindump; I'm trying to show the thought process I'm having based on the documentation. If you can point me to a good description ([Processing's color datatype page](https://www.processing.org/reference/color_datatype.html) helps a bit, but doesn't talk about the difference between int and float), I'm happy to write new docstrings and submit them here. Thanks.

**Comment by GoToLoop** [comment]
Source code w/ all **color()** overloaded signatures:
https://github.com/processing/processing/blob/processing-0265-3.4/core/src/processing/core/PApplet.java#L10269-L10382

Also the JavaDocs for the _**PApplet**_ class:
http://processing.github.io/processing-javadocs/everything/processing/core/PApplet.html

**Comment by nbeloglazov** [comment]
I actually broke some things with my commit (in particular `current-fill` currently doesn't work correctly but I'm going to fix it). But yes, I decided to clean up API to make clj and cljs versions more aligned and remove  some confusion. Alex, thanks for bringing up the issue! I'll close it as it's no longer relevant.

**Comment by zck** [comment]
Yeah, it certainly is cleaner if there's no `fill-int` or `fill-float`. cheers! I do think the documentation might make it more obvious why I should care that it casts the argument as a float. Cheers!
