### ISSUE TITLE
IllegalArgumentException Don't know how to create ISeq from: java.lang.Boolean  clojure.lang.RT.seqFrom (RT.java:550)

### ISSUE THREAD

**Issue by jurb** [quil/quil#253]
I'm new, and just followed the following from the tutorial:

1. Installed the Java SDK from oracle (10.0.2)
2. Installed `brew install clojure`
3. Installed `brew install leiningen`
4. Ran `lein new quil my-sketch`
5. Went into the dir and ran `lein repl`
6. Ran `(use 'my-sketch.core :reload-all true)`

Got

`IllegalArgumentException Don't know how to create ISeq from: java.lang.Boolean  clojure.lang.RT.seqFrom (RT.java:550)`

**Comment by jurb** [comment]
@nbeloglazov Thanks. That outputs `nil`

**Comment by nbeloglazov** [comment]
It should also start a sketch. If you don't see it, can you check background windows?

**Comment by jurb** [comment]
I don't see any window appearing unfortunately. Using macos and zsh on iterm2. I also tried the stock terminal.app and bash, to no avail.

**Comment by nbeloglazov** [comment]
Can you insert your my_sketch/core.clj here? Also can you add `(println "Hello, world")` there and run it? To make sure that you see Hello World printed in console.

**Comment by jurb** [comment]
Running `(println "Hello, world")` prints out

```
Hello, world
nil
```

in the REPL.

I haven't edited my `core.clj` but only created it with `lein new quil ` as far as I know, but here it is:

```
(ns my-sketch.core
  (:require [quil.core :as q]
            [quil.middleware :as m]))

(defn setup []
  ; Set frame rate to 30 frames per second.
  (q/frame-rate 30)
  ; Set color mode to HSB (HSV) instead of default RGB.
  (q/color-mode :hsb)
  ; setup function returns initial state. It contains
  ; circle color and position.
  {:color 0
   :angle 0})

(defn update-state [state]
  ; Update sketch state by changing circle color and position.
  {:color (mod (+ (:color state) 0.7) 255)
   :angle (+ (:angle state) 0.1)})

(defn draw-state [state]
  ; Clear the sketch by filling it with light-grey color.
  (q/background 240)
  ; Set circle color.
  (q/fill (:color state) 255 255)
  ; Calculate x and y coordinates of the circle.
  (let [angle (:angle state)
        x (* 150 (q/cos angle))
        y (* 150 (q/sin angle))]
    ; Move origin point to the center of the sketch.
    (q/with-translation [(/ (q/width) 2)
                         (/ (q/height) 2)]
      ; Draw the circle.
      (q/ellipse x y 100 100))))

(defn -main [& args]
  (q/defsketch my-sketch
    :title "You spin my circle right round"
    :size [500 500]
    ; setup function called only once, during sketch initialization.
    :setup setup
    ; update-state is called on each iteration before draw-state.
    :update update-state
    :draw draw-state
    :features [:keep-on-top]
    ; This sketch uses functional-mode middleware.
    ; Check quil wiki for more info about middlewares and particularly
    ; fun-mode.
    :middleware [m/fun-mode]))
```

**Comment by nbeloglazov** [comment]
Ooops, thanks. The issue is with "(defn -main" thing. We added it but forgot to update docs and thinking now it probably shouldn't have been added in the first place. So you have 2 options:

1. Use `lein run` to run sketch.
2. Remove `(defn -main ...)` wrapper so that (q/defsketch ...) is on top level and do the thing you tried.

**Comment by nbeloglazov** [comment]
Ohh, you are using jdk 10. Quil currently doesn't support it. It uses Processing internally and Processing is not supporting JDK above 8 unfortunately. See #250 for example.

**Comment by Jedzia** [comment]
### A New User Experience + From your README.md:

> lein new quil hello-quil
> Then go to hello-quil/src/hello-quil/core.clj file and run it!

Is it too much to specify that command how to run it?

### First steps with https://github.com/quil/quil/wiki/Installing
λ javac -version -> javac 1.8.0_112

    lein new quil my-art
    ...
    lein repl
    ...
    Clojure 1.10.1
    Java HotSpot(TM) 64-Bit Server VM 1.8.0_231-b11
    ...
    user=> (use 'my-art.core :reload-all true)
    Execution error (IllegalArgumentException) at user/eval1522 (form-init308350672940658712.clj:1).
    Don't know how to create ISeq from: java.lang.Boolean

So reload does not work with JDK8 either.

I don't know what I am doing, but `lein run` doesn't work, too. This is exactly how a new user experience should be: horrible.
Excuse me, got a little angry. That is not your fault:)

**Comment by nbeloglazov** [comment]
I believe it's just `(use 'my-art.core :reload-all)` without `true`. Check examples here: https://clojuredocs.org/clojure.core/use In fact `(require 'my-art.core :reload-all)` seems to work better as I'm not getting IllegalStateException but sketch still restarts with each `require`.

> Is it too much to specify that command how to run it?
That's fair. Instructions on http://quil.info also don't specify how to run it. I didn't add commands as clojure has many way to run code (lein repl, lein run, emacs, lightable, etc). But it makes sense to provide basic `lein repl` and then `(require ...)` flow.

**Comment by Jedzia** [comment]
Thanks for your response.
I tested it without the Boolean specifier `true`, too and the on-the-fly reload didn't work. That was the feature i was curios about in the first place.
Give me some time to bring my skills up to date. That i am not so useless like in the other comment and can specify what is actually happening on my side:)
