### ISSUE TITLE
(q/texture) causes "curContext.createTexture is not a function" error

### ISSUE THREAD

**Issue by buntine** [quil/quil#254]
Any mention of the texture function when drawing causes an error when running in CLJS.

For example, the following simple draw function will fail (assume that :animage is an image previously loaded via (q/load-image):

```
(defn draw [state]
   (q/begin-shape)
   (q/texture (:animage state))
   (q/vertex 0 0)
   (q/vertex 100 0)
   (q/vertex 100 100)
   (q/vertex 0 100)
   (q/end-shape)))
```

In Firefox and Chromium I get: 
```
Uncaught TypeError: curContext.createTexture is not a function
```

**Comment by buntine** [comment]
Upon further inspection it seems that perhaps this is a bug with Processing.js itself: https://github.com/processing-js/processing-js/issues/177

Reading that is worrying as it seems Processing.js is no longer actively developed and seems to have been superceded by p5js.

I wonder - is there a plan to move towards p5js and away from Processing.js?

**Comment by nbeloglazov** [comment]
Thanks for the bug report. Yes, we should migrate to p5js. I was reluctant to do it because it's quite a big change and I have concerns around API differences. Though poking through p5js reference it seems like most quil/processing.js functions are present there as well. Filed #255 I guess I'll keep this bug open until we migrate to p5js

**Comment by buntine** [comment]
No worries. I am happy to help out with some of the grunt work involved with the switch.

**Comment by nbeloglazov** [comment]
That would be great! Some of the grunt work is to compare Quil API (http://quil.info/api) with p5js API and create a spreadsheet that lists which function removed/added/mismatch. Also if you are not familiar with p5js (like me) it would be useful to build some sketches in p5js and look into p5js code as it will be very useful for the migration.

**Comment by anthonygalea** [comment]
As of quil 3.0.0 [texture](http://quil.info/api/shape/vertex#texture) is supported in cljs. Migrated from processing.js to p5js. See https://github.com/quil/quil/issues/255 for more details.
