### ISSUE TITLE
Migrate from processing.js to p5js

### ISSUE THREAD

**Issue by nbeloglazov** [quil/quil#255]
Processing.js is no longer being developed and new bugs are not fixed. It was superseded by p5js and we should change quill to use p5js under the hood.

**Comment by nbeloglazov** [comment]
Plan for the migration:

- [ ] Clone and look at p5js codebase.
- [ ] Convert quil basic example into p5js.
- [ ] Compare Quil API with p5js API to see if some methods needs to be removed/added. 
- [ ] Draft changes to use p5js API instead of procesing.js
- [ ] Write externs file for p5js.
- [ ] Come up with a way to use support both p5js and processing.js temporarily.
- [ ] Clean up and submit changes to use p5js API.
- [ ] Run cljs tests with p5js enabled. Check that docs still make sense.
	- [ ] Color, creating & reading
	- [ ] Color, setting
	- [ ] Color, utility macros
	- [ ] Typography, attributes
	- [ ] Typography, loading & displaying
	- [ ] Typography, metrics
	- [ ] Image
	- [ ] Image, loading & displaying
	- [ ] Image, pixels
	- [ ] Image, rendering
	- [ ] Transform
	- [ ] Transform, utility macros
	- [ ] Rendering
	- [ ] Rendering, shaders
	- [ ] Math, calculation
	- [ ] Math, random
	- [ ] Math, trigonometry
	- [ ] Data
	- [ ] State
	- [ ] Shape, 2d primitives
	- [ ] Shape, 3d primitives
	- [ ] Shape, Attributes
	- [ ] Shape, curves
	- [ ] Shape, loading & displaying
	- [ ] Shape, vertex
	- [ ] Lights & camera, camera
	- [ ] Lights & camera, coordinates
	- [ ] Lights & camera, light
	- [ ] Lights & camera, material properties
	- [ ] Environment
	- [ ] Input, keyboard
	- [ ] Input, mouse
	- [ ] Input, time & date
	- [ ] Output, files
	- [ ] Output, image
	- [ ] Output, text area
	- [ ] Structure
	- [ ] Middleware
- [ ] Write docs how to switch to processing.js for testing. 
- [ ] Publish p5js in clojars.
- [ ] Release new quil version.

**Comment by anthonygalea** [comment]
Took some time to look into this.

As I understood this would be the [basic quil example in p5](https://gist.github.com/anthonygalea/bbeec298e7c7a5f5c6ae6a06a78c151f)

After [comparing APIs](https://gist.github.com/anthonygalea/1cc3f09a694bb90ce46566feb4dfe9e1) I drafted some of the [changes](https://github.com/anthonygalea/quil/commit/e92c6df521d75859fe01ad0b303b8989b019a2a8) just to see what it would look like to replace processing with p5. :warning: This does not support both libraries. Not sure how to go about doing that.

For testing I'm [comparing the snippets](https://gist.github.com/anthonygalea/610ac0a679220e70d347d32f7cfccbd0) before and after side by side.

For externs I'm using [cljsjs/p5](https://github.com/cljsjs/packages/tree/master/p5). Sent a [pull request](https://github.com/cljsjs/packages/pull/1765) to upgrade to latest p5 yesterday.

At this point it would be great to get some feedback to see if I'm headed in the right direction.

**Comment by nbeloglazov** [comment]
Wow, that's impressive work, Anthony! Some thoughts:

Comparing APIs: maybe move this list to a google doc or spreadsheet so that it can be edited/commented by multiple people. Will be useful to discuss what to do with added/removed functions.

Draft changes: that actually looks pretty reasonable. I expected more drastic changes, glad to see that we probably won't need to rewrite sketch.cljs much. As for the flow: how about we create a branch on quil for p5js and commit changes there. I think we start with the basic changes to sketch.cljs and util.cljs without updating any snippets or core.cljc (which means the test will fail, but that's ok) and then incrementally test/fix API functions and corresponding snippets? 

Supporting both p5js and processing.js: that would be cool, but maybe it will involve too much complexity without any clear benefits. As Quil developer it'd be useful to quickly check regressions, but for Quil users it probably is not very important. So maybe we can omit this requirement. 

cljsjs/p5 and externs: didn't about that, glad that we can reuse existing library instead of creating our own p5js clojar. 

What do you think?

**Comment by anthonygalea** [comment]
Thanks.
Sounds good, here's the [spreadsheet](https://docs.google.com/spreadsheets/d/1LlXS5DuMgSZpV5LSwvmYzSr5Tpm8UUxwfsuSAsDSamE/edit?usp=sharing).
Regarding flow sounds good.
Regarding supporting both libraries I was thinking the same because if an end user wants to use processing.js he can simply stick to an older version of quil.

**Comment by anthonygalea** [comment]
This would be the [first commit](https://github.com/anthonygalea/quil/commit/029d1c58e77090776fccd77cfc50863a45faa128) on p5js branch. Did I understand correctly that you want to do this in the main quil repo or should I just continue in my fork and then send you a pull request?

**Comment by anthonygalea** [comment]
You will probably want to add adapting the [lein template](https://github.com/quil/quil-templates/blob/master/cljs/src/leiningen/new/quil_cljs/resources/public/index.html) for cljs the todo list above. i.e. `div` instead of `canvas`.

**Comment by nbeloglazov** [comment]
Quil 3.0.0 has been released that switches to p5js. Big thanks to @anthonygalea who did most of the heavy lifting for this release. It's time to close this bug.
