### ISSUE TITLE
Fonts are reset on draw in quil-cljs

### ISSUE THREAD

**Issue by larstvei** [quil/quil#258]
Hi!

I am able to load fonts using:

```clojure
(q/text-font (q/create-font "monospace" 12))
```

If I place this in the `setup` function, then the font is reset to the default font on the next draw. For now, I've placed it in the `draw` function, and that works fine. But as I understand the documentation, this shouldn't be necessary?

**Comment by nbeloglazov** [comment]
That's a good question. Yes, I'd expect that text-font would work in setup but maybe there is some oddity in processing.js. Given that processing.js is in maintenance mode and not actively fixing bugs I doubt it would be fixed there. And we are going to migrate to p5js in future. I'll leave this bug open to verify that it's fixed after p5js migration.

**Comment by nbeloglazov** [comment]
That's a good question. Yes, I'd expect that text-font would work in setup but maybe there is some oddity in processing.js. Given that processing.js is in maintenance mode and not actively fixing bugs I doubt it would be fixed there. And we are going to migrate to p5js in future. I'll leave this bug open to verify that it's fixed after p5js migration.

**Comment by larstvei** [comment]
Sounds good. I'm really looking forward to the p5js migration!

**Comment by anthonygalea** [comment]
Hi Lars, p5js migration was [done](https://github.com/quil/quil/issues/255) and released as part of quil 3.0.0. Can you please test setting font in the `setup` function with quil 3.0.0?

**Comment by larstvei** [comment]
Looks like it's [working](http://quil.info/sketches/show/60b7719adbf60e95087673a506b0810c0f36a58fb7eb676d75691814d7370a60)!
