### ISSUE TITLE
with-translation in x-axis

### ISSUE THREAD

**Issue by ampersanda** [quil/quil#259]
I read the following API docs and it says that `with-translation` accepts a vector `[angle]` or `[angle x-axis y-axis z-axis]` (this is for 3d mode right?). What is `angle` in the first of the vector (for 3d mode) or do I miss something about this docs?

Thank you

**Comment by ampersanda** [comment]
I use rotate-x instead

**Comment by nbeloglazov** [comment]
Hi Mochamad. It's a very good question. And actually I don't know. I tracked it all the way to Processing and and they just refer it to opengl glRotate function: https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glRotate.xml Given that it's pretty non-obvious function we probably should remove it from API.

**Comment by nbeloglazov** [comment]
I looked more into it and I think 4 parameters are actually ok to understand: you provide a vector x, y, z and tell it to rotate around that vector. Added docs to clarify and also improved examples. Once #246 is done it should be easier to see examples and try them.
