### ISSUE TITLE
Space key mapped to unusable keyword by key-as-keyword

### ISSUE THREAD

**Issue by tkocmathla** [quil/quil#262]
The space key is mapped by key-as-keyword to a keyword whose name is the literal space, which is not valid Clojure syntax. E.g.,

`(q/key-as-keyword)
=> : `

Should I handle key this with key-code, or would it make sense to change key-as-keyword to return :space instead?

**Comment by nbeloglazov** [comment]
Good point. Yes, we should change it to `:space`. I think I stubmled upon this issue a while ago too, but never followed with a proper fix.

**Comment by tkocmathla** [comment]
I looked into making this change but I'm not sure about the best way to do it. The space key isn't coded, so I don't think I can just add it to the KEY-CODES map. Handling it as a special one-off in the key-as-keyword fn seems wrong if there might be other keys that have the same issue (I noticed the enter key on PC created an invalid keyword too). Would it make sense to have a new top-level map like KEY-CODES to do secondary look-ups in?

**Comment by nbeloglazov** [comment]
Yes, I think it's reasonable. I agree that it's not ideal that we'll have 2 lookups maps but I can't think of a better solution. I don't fully understand the concept of "coded" key but I assume it's needed and we can't easily rework it to have a single map.
