### ISSUE TITLE
Setting q/color colors not working in Clojure

### ISSUE THREAD

**Issue by pgorczak** [quil/quil#267]
It looks like Quil for Clojure does not handle colors created with q/color correctly. When running the [q/color example](http://quil.info/api/color/creating-and-reading#color) in Clojure, the first three rectangles are black and the last one is white with a black stroke. Calls to q/fill and q/stroke work properly when called with numeric args though.

*Edit:* Just checked the previous version too. When going back to 2.7.1, the example works as intended.

**Comment by nbeloglazov** [comment]
Thanks, Philipp! I broke accidentally during last release. The fix will be in the next release.
