### ISSUE TITLE
Extending Wiki pages Dynamic Workflow (for REPL) / Functional Mode: How to

### ISSUE THREAD

**Issue by jradek** [quil/quil#271]
Hi,

I'm new to quil and had some trouble so setup the workflow. The wiki pages are very helpful, but they didn't answer all my questions (as a novice). After lot of googling and asking in slack/reddit, I found answers to my questions, which are also written down [here](https://www.reddit.com/r/Clojure/comments/afazxb/repl_workflow_in_quil/edzeyp4). So maybe this is valuable for other new users like me as well. Thats why I wanted to extend the wiki pages.
How can I do that? Simply modify them?

JR

**Comment by jradek** [comment]
I applied all my changes to the wiki pages

**Comment by nbeloglazov** [comment]
Thanks! Sorry, I missed this bug.
