### ISSUE TITLE
Is there a "shuffle collection" function?

### ISSUE THREAD

**Issue by zck** [quil/quil#274]
Clojure has [a method](https://clojuredocs.org/clojure.core/shuffle) to randomly permute the collection passed to it as an argument. I don't see anything like this in Quil; is there a way to do that?

**Comment by nbeloglazov** [comment]
Use clojure built-in function that you found. Quil doesn't aim to replace standard clojure functions even though some like sin/cos indeed replace Math/sin Math/cos, but it's left from the beginnings of Quil. If we were implementing Quil from scratch now we'd probably didn't include all functions that mirror some standard clojure functions.

**Comment by zck** [comment]
I was looking for a method to do this in Quil for reproducibility, the way "random" works. There's a `random` function provided in quil; I assumed that `quil/random` used quil's [random seed](http://quil.info/api/math/random#random-seed), but [`clojure.core/random`](https://clojuredocs.org/clojure.core/rand) didn't.

Is that inaccurate? Do I never need to use `quil/random` if I don't need the two-argument version? That would mean I could use clojure's built-in shuffle.

**Comment by nbeloglazov** [comment]
Reproducibility is a fair point. Personally I've been using clojure rand/rand-int as I didn't need reproducibility. But if you need it - hm. Maybe there are other clojure libraries that can do that?
