### ISSUE TITLE
PNG with Transparent Background

### ISSUE THREAD

**Issue by tmountain** [quil/quil#283]
Hi, I'm trying to use Quil to produce a PNG with no background. So far, nothing has worked. Any help would be appreciated. Thanks!

    (defn draw []
      (let [gr (q/create-graphics 300 300 :java2d)]
        (q/with-graphics gr
          ;(q/background 0 0)
          (q/stroke 0 0 0)
          (q/stroke-weight 1.5)
          (q/rect 182 75 59 59 4)
          (q/image gr 0 0)
          (q/save "test.png")))

**Comment by anthonygalea** [comment]
To me it seems your example works as intended. Used it to generate the png below. Do you get no image at all or a different output?
![test](https://user-images.githubusercontent.com/1301852/53762373-3c720f00-3ec8-11e9-9cf0-cecb6c2aa7f7.png)

**Comment by tmountain** [comment]
I just tested it myself, and it's working. Not sure what I was doing wrong. Apologies for the false alarm! Full working example below in case anyone bumps into this looking for how to do transparency with quil.

```
(ns derp.core
  (:require [quil.core :as q]
            [quil.middleware :as m]))

(defn draw-state [state]
  (let [gr (q/create-graphics 300 300 :java2d)]
    (q/with-graphics gr
      (q/stroke 0 0 0)
      (q/stroke-weight 1.5)
      (q/rect 182 75 59 59 4)
      (q/image gr 0 0)
      (q/save "test.png"))))

(q/defsketch derp
  :title "You spin my circle right round"
  :size [500 500]
  :draw draw-state
  :middleware [m/fun-mode])
```
