### ISSUE TITLE
Reducing reflection

### ISSUE THREAD

**Issue by heyarne** [quil/quil#286]
I wrote a small sketch today and used the super handy macro `(q/with-graphics ,,,)`. Trying to improve the speed I noticed some reflection warnings, most of which were fixed by type-hinting the `PGraphics` objects that were used. This made me think that it might be useful to rewrite the macro to add these automatically – would that be something worth investigating? I don't know if the type-hint would be too strict because I'm not very familiar with Processing's architecture, or if there are other macros for which one might also want to add annotations. Any thoughts?

**Comment by nbeloglazov** [comment]
Yes, adding type hint would be great. It should be safe to do so as only `PGraphics` should be passed to `with-graphics` macro.

**Comment by nbeloglazov** [comment]
Checked other macros and they are ok: only `with-graphics` uses java interop to call methods via `(.foo obj)`.

**Comment by heyarne** [comment]
I'm not exactly sure how to deal with ClojureScript here; I get warnings when trying to compile it with or without the annotation (using `lein with-profile cljs-testing cljsbuild auto development`). I added the simple annotation `^PGraphics` into the macro (I don't know if that'll be resolved to the `PGraphics` in the externs file of `quil/processingjs`); the compilation errors stay the same.

[compilation-log.txt](https://github.com/quil/quil/files/2975109/compilation-log.txt)

**Comment by nbeloglazov** [comment]
Try running `lein compile` before that.

**Comment by nbeloglazov** [comment]
And if I remember correctly type hints are ignored in cljs.

**Comment by heyarne** [comment]
`lein compile` solved the issues, I'll open a pull request!
