### ISSUE TITLE
Editor breaks code

### ISSUE THREAD

**Issue by maacl** [quil/quil#293]
When I paste below 1) valid form into the editor it is promptly broken and turned into 2):

1)
```
(defn setup []
  (q/color-mode :rgb)
  {:planets [{:name "earth"
              :size 18
              :color [0, 200, 0]
    	      :x -149.6e9
    	      :y 0
    	      :xp 0
    	      :yp 3e4
              :xpp 0
              :ypp 0
    	      :m 5.972e24}
             {:name "mars"
              :size 10
              :color [255, 160, 0]
              :x 227.9e9
              :y 0
              :xp 0
              :yp (/ -86.871e6 3600)
              :xpp 0
              :ypp 0
              :m 6.39e23}
             {:name "sun"
              :size 40
              :color [255, 210, 0]
    	      :x 0
              :y 0
              :xp 0
    	      :yp 0
              :xpp 0
              :ypp 0
    	      :m 1.989e30}]
   :space-ship {:name "bfr"
                :size 4
                :xpp 0
                :ypp 0
                :m 10e5
                :color [190, 190, 190]
                :brake-start 432e5
                :brake-end 459.0e5
                :position-history []}
   :t 0
   :dt 1e5
   :launch-t 376e5
   :G 6.67408e-11})
```
2)
```
(defn setup []
  (q/color-mode :rgb)
  {:planets [{:name "earth"
              :size 18
              :color [0, 200, 0]}]
            :x -149.6e9
            :y 0
            :xp 0
            :yp 3e4
              :xpp 0
              :ypp 0
            :m 5.972e24
             {:name "mars"
              :size 10
              :color [255, 160, 0]
              :x 227.9e9
              :y 0
              :xp 0
              :yp (/ -86.871e6 3600)
              :xpp 0
              :ypp 0
              :m 6.39e23}
             {:name "sun"
              :size 40
              :color [255, 210, 0]}
            :x 0
              :y 0
              :xp 0
            :yp 0
              :xpp 0
              :ypp 0
            :m 1.989e30
   :space-ship {:name "bfr"
                :size 4
                :xpp 0
                :ypp 0
                :m 10e5
                :color [190, 190, 190]
                :brake-start 432e5
                :brake-end 459.0e5
                :position-history []}
   :t 0
   :dt 1e5
   :launch-t 376e5
   :G 6.67408e-11})
```

**Comment by nbeloglazov** [comment]
It's probably related to https://github.com/quil/quil-site/pull/23 @urzae, do you have any ideas?

**Comment by nbeloglazov** [comment]
Oh, actually the code contains mix of spaces and tabs which probably confuses parinfer and it incorrectly rewrites the code.

**Comment by maacl** [comment]
I removed all tabs and the problem persists. I have also tried to use only tabs, and the problem still persists. Would adding an option to switch off parinfer be an option?

**Comment by maacl** [comment]
Sorry I thought emacs untabify would fix it. Now I have below issue (free from tabs).

This:

```
(defn update-planet [dt]
   (fn [{:keys [x y xp yp xpp ypp] :as p}]
    (let [xp (+ xp (* xpp dt))
          yp (+ yp (* ypp dt))
          x  (+ x (* xp dt))
          y  (+ y (* yp dt))]
          (assoc p :xp xp :yp yp :x x :y y :xpp 0 :ypp 0))))
```

gets replaced with this:

```
(defn update-planet [dt]
   (fn [{:keys [x y xp yp xpp ypp] :as p}]
    (let [xp (+ xp (* xpp dt))
          yp (+ yp (* ypp dt))
          x  (+ x (* xp dt))
          y  (+ y (* yp dt))
          (assoc p :xp xp :yp yp :x x :y y :xpp 0 :ypp 0)])))
```

**Comment by nbeloglazov** [comment]
That seems quite odd. Parinfer treats formatting of pasted text higher than actual parenthesis? Anyway, @urzae I think we should disable auto-formatting for now and instead add an option to enable it (e.g. using checkbox). Could you look into it? Or alternatively figure out why parinfer behaving weirdly, but that might take more time to figure out and fix.

**Comment by anthonygalea** [comment]
@nbeloglazov parinfer supports 2 modes:
1. indent mode (this is the one the editor is using)
> ... gives you full control of indentation, while Parinfer corrects or inserts close-parens where appropriate.
2. paren mode
> gives you full control of parens, while Parinfer corrects indentation. 

It is very well explained here: https://shaunlebron.github.io/parinfer/#tools-for-writing-lisp and based on your comment it seems you happen to prefer paren mode.

@maacl while you are of course free to write your `let` blocks however you like :) `let` blocks are commonly indented like this:
```clojure
(let [x (+ x (* xp dt))
      y (+ y (* yp dt))]
  (assoc...))
```
Notice the `assoc` is not aligned with the bindings, but instead just indented 2 spaces within the `let`. If you indent like this the editor will automatically correct the parenthesis and the code is also more readable because the bindings are clearly distinguished from the let body.

Another option if you like (since you mentioned emacs) is to [set up parinfer within emacs](https://github.com/DogLooksGood/parinfer-mode), set it to paren mode (if you prefer that mode), and when you paste into the editor there shouldn't be any changes.

Hope this helps.

**Comment by maacl** [comment]
Thanks. I have tried parinfer in Emacs before but switched it of again.
Maybe I should just confirm 😀.
