### ISSUE TITLE
clojurescript y axes upside down

### ISSUE THREAD

**Issue by olymk2** [quil/quil#297]
Finding this a bit confusing,  

Y seems inverted in clojurescript looking at some of the examples they do not have this issue.

So in examples I see this to centre the sketch
     (q/with-translation [(/ (q/width) 2) (/ (q/height) 2)]

I am finding I need todo this to achieve the same ie make everything negative

     (q/with-translation [(/ (q/width) 2) (/ (* -1  (q/height)) 2)]

Am I missing something or is this expected ? is there a simple way to flip the y in quil with a transform if not ?

**Comment by nbeloglazov** [comment]
Hi Oliver. Could you elaborate a little bit or provide full example? In quil (both clj and cljs) the center of coordinates, point 0,0 is the top left corner (https://processing.org/tutorials/drawing/). Using negative value for y coordinate seems unusual as I'd expect it to go out of sketch bounds.

Here is quil cljs example that draws circle in the center of screen: http://quil.info/sketches/show/64d2f591bf1422a24bdf489fd2921a8898c9caa4e86770e4644d593bfc2c25a7

**Comment by olymk2** [comment]
Okay great that shows it perfectly, just add this line.         
    
    (q/line 0 0 0 100)

Could be this is how it is basically 0 is the center drawing by 100 in the y axes goes down the page not up the page hence why I have to flip everything, my brain does not work well in upside down :)

If this is how things are supposed to be is there a simple flip transform I can do with quil so i don't have to multiply by -1 everywhere to make my values negative ?

**Comment by nbeloglazov** [comment]
You can use [apply-matrix](http://quil.info/api/transform#apply-matrix) function. It allows you to do custom transformation of x/y coordinates. For example if you use clojurescript version, you can call apply-matrix as `(q/apply-matrix 1 0 0 -1 0 0)` which multiplies x by 1 and multiplies y by -1. 

Here is an example: http://quil.info/sketches/show/474561d71cca52dd5abd5d59dd2a25f70c83e99bc095c8481787da932d588dfb

If you working with clojure I parameters of `apply-matrix` slightly different (I think order of matrix elements is different) but you can achieve the same result after some tinkering.

**Comment by olymk2** [comment]
okay great thanks for the example @nbeloglazov most appreciated I will have a play with that, is there a reason why up is down and down is up out of interest or is that just how p5j works, using clojurescript by the way :)

**Comment by nbeloglazov** [comment]
That's how all graphics in computers work pretty much when you draw
programmatically.
