### ISSUE TITLE
Add logging functions for debugging

### ISSUE THREAD

**Issue by nbeloglazov** [quil/quil#315]
Debugging Quil sketches is quite hard. Often you need to see state of the sketch but adding `println` to sketch causes never ending stream of text in console. Quil should provide some functionally to aid debugging. For example we could add `print-first-n` function that when called prints provided arg only the first `n` iterations. Similarly we could add `print-every-n-sec` to see samples during sketch run.

**Comment by anthonygalea** [comment]
Is this what you have in mind?
```clojure
(def p (volatile! nil))

(defn print-first-n
  [n & more]
  (locking p
    (when (nil? @p)
      (vreset! p n))
    (when (pos? @p)
      (vswap! p dec)
      (apply print more))))
```
You can see it in use in this sketch: http://quil.info/sketches/show/7f7cc14db3a5ba44cb528cb7f3fd69763cabf8e53183f13bb8ba9e5a8ac35469

**Comment by nbeloglazov** [comment]
Yes, something like that. Though we can use `frame-count` instead of mutable object to keep things simpler. Otherwise you'd need to store the `p` on sketch itself as it can't be global?

**Comment by anthonygalea** [comment]
Ah yes, using `frame-count` is a lot better:
```clojure
(defn print-first-n
  [n & more]
  (when (<= (q/frame-count) n)
    (apply print more)))
```

Regarding printing every n seconds, do you see an alternative to the following approach which requires storing the `last-time`?
```clojure
(def last-time (atom 0))

(defn print-every-n-millisec
  [n & more]
  (let [elapsed (q/millis)]
    (when (< n (- elapsed last-time))
      (reset! last-time elapsed)
      (apply print more))))
```

**Comment by nbeloglazov** [comment]
Trying to think if we can avoid atom, but can't think of any approach. So probably yeah - that would be the way to do it. The only thing I mentioned before, it would be good if `last-time` is tied to sketch instead of being global variable shared between all sketches.

**Comment by nbeloglazov** [comment]
We have [internal-state](https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L191) function for similar purposes (though doc string lies, this state should *not* be visible to users).
