### ISSUE TITLE
Using 3.0.0 sketch fn with :host dom-node/component for embedding into reagent. 

### ISSUE THREAD

**Issue by samirsa** [quil/quil#320]
Hello all,
I was using https://github.com/yogthos/quil-reagent-demo to create a starter reagent+quil project. It seemed to work well, with the dependencies as follows - 

```
 :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.10.339"]
                 [reagent "0.8.1"]
                 [quil "2.7.1"]]
```

however, when I upgrade to the latest quil version of 3.0.0 (or even 3.1.0-SNAPSHOT), the setup does not work. 

The only difference from this and the other quil-template demo seems to be the use of the host node - Using the component instead of a div id. 

```
(defn canvas []
  (r/create-class
    {:component-did-mount
     (fn [component]
       (let [node (r/dom-node component)
             width (.-width node)
             height (.-height node)]
         (q/sketch
           :host node
           :draw draw
           :setup (init width height)
           :update update-state
           :size [width height]
           :middleware [m/fun-mode])))
     :render
     (fn []
       [:canvas {:width  (/ (.-innerWidth js/window) 2)
                 :height (/ (.-innerHeight js/window) 2)}])}))
```

I tried creating a new reagent project (not using the quil-reagent-demo linked up), and tried to add a quil sketch to it. The results seemed the same - where if I link to the div id, then it shows up, but I would like to link it to a component (so that it can be controlled via the reagent framework - displayed moved etc.) 

Were there any changes in recent quil release which changed this behavior? Or any ideas on how to get a quil sketch working as a reagent node? 

PS - I am slightly new to the reagent/quil world of clojurescript, and might be making a noob mistake. 

thanks in advance.

**Comment by ampersanda** [comment]
Hey, I checked your repo and I found that `quil 2.7.0` creates (probably replace) canvas using the node that `component-did-mount` returned.

![Screen Shot 2019-09-25 at 12 16 56](https://user-images.githubusercontent.com/13579812/65571402-cb429800-df8e-11e9-8ec2-9b7f1f0f5a44.png)

And `quil 3.0.0` creates canvas inside the canvas (append?, I think that's the problem)

![Screen Shot 2019-09-25 at 12 21 07](https://user-images.githubusercontent.com/13579812/65571445-f88f4600-df8e-11e9-9cdf-c25bd5f26dad.png)

so changing `canvas` to another html tag will solve the problem.

```clj
(defn canvas []
  (let [width  (/ (.-innerWidth js/window) 2)
        height (/ (.-innerHeight js/window) 2)]
    (r/create-class
     {:component-did-mount
      (fn [component]
        (let [node   (r/dom-node component)]
          (q/sketch
           :host       node
           :draw       draw
           :setup      (init width height)
           :update     update-state
           :size       [width height]
           :middleware [m/fun-mode])))
      :render
      (fn []
        [:div])})))
```

**Comment by samirsa** [comment]
Thanks. This worked great.

**Comment by nbeloglazov** [comment]
Thanks for figuring it out, @ampersanda. Yes, starting from Quil 3.0 divs should be instead instead of canvas: https://github.com/quil/quil/blob/master/RELEASE-NOTES.md#300
