### ISSUE TITLE
How to get mouse-wheel function working?

### ISSUE THREAD

**Issue by samirsa** [quil/quil#321]
I am trying a simple example at http://quil.info/sketches/show/49b60a4e498a0e597aabf229c139e5c347babf26225df013556fef569b3cf810

The mouse-click works, but the mouse-wheel function does not seem to. 

Am I missing something? 

thanks.

**Comment by nbeloglazov** [comment]
Indeed it doesn't seem to work in cljs version. I tried running your sketch without changes in clj and it works. Maybe we broke it during p5js migration. @anthonygalea do you remember if tested all key/mouse handlers?

**Comment by nbeloglazov** [comment]
Looking at https://docs.google.com/spreadsheets/d/1LlXS5DuMgSZpV5LSwvmYzSr5Tpm8UUxwfsuSAsDSamE/edit#gid=0 we missed mouseWheel (lines 254-259).

**Comment by anthonygalea** [comment]
Don't remember testing `mouseWheel` @nbeloglazov. But I also don't see `mouseWheel` in the  [processing js reference](http://processingjs.org/reference/). Can it be that this was only supported in clj?

In any case I see a [mouseWheel in the p5 reference](https://p5js.org/reference/#/p5/mouseWheel) so it should be possible to add it with p5.

**Comment by nbeloglazov** [comment]
Fixed. Thanks @samirsa for reporting!
