### ISSUE TITLE
 Is it possible to inspect the state in fun-mode in Quil using the REPL?

### ISSUE THREAD

**Issue by gtoast** [quil/quil#324]
See title.  Experimenting with fun-mode middleware and want to inspect the state that's being passed around. 

Is it possible to pause execution and inject a new state from the repl?

**Comment by nbeloglazov** [comment]
Hi Changa. There is no simple way to do it but you can build it yourself relying on the fact that sketch and repl run in different threads. The main idea is to pause sketch thread and wait until repl thread provides new state. You can do it using clojure promise. Something like:

```clojure

(def pause-next-cycle (atom false))
(def current-state (atom nil))
(def new-state-promise (atom nil))

(defn update-state [state]
  (if @pause-next-cycle
    (do 
      ; reset pause flag so that sketch will keep running after new state is delivered
      (reset! pause-next-cycle false)
      ; save current state in atom that is accessible from repl
      (reset! current-state state)
      ; create new promise that will contain new state set from repl
      (reset! new-state-promise (promise))
      ; dereference atom and promise thus blocking sketch thread
      ; until promise is delivered from repl
      @@new-state-promise))
    ; do normal state update here
    ...)))

```

and here is how to use it from repl:

```clojure
; tell sketch to pause on next iteration
> (reset! pause-next-cycle true)

; inspect state
> (printn @current-state)

; set new state which will unpause sketch
> (deliver @new-state-promise {:hello :world})
```

I haven't tested it but pretty sure it will work.

**Comment by gtoast** [comment]
This is amazing! But any idea how this would be done in ClojureScript. I've been banging my head against Promises in ClojureScript and I'm hung up on how to resolve the Promise inside an atom.

**Comment by nbeloglazov** [comment]
In JS you can't block thread as there is only one thread. Instead you might need to use `q/no-loop` and `q/start-loop` functions to pause and unpause sketch. If you need to unpause sketch from "outside" sketch use [with-sketch](https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L170) macro. Here is a kinda example of how to start sketch using this macro: [code](https://github.com/quil/quil/blob/master/test/cljs/quil/manual.cljs#L14).

**Comment by gtoast** [comment]
THANK YOU!
