### ISSUE TITLE
NPE on exit from sketch using :pdf renderer

### ISSUE THREAD

**Issue by gonewest818** [quil/quil#325]
Writing an issue because I might not have the time to fix; but want to leave some bread crumbs in case others are interested.

I have a sketch that computes and writes a pdf file. The computation part of the sketch works fine, but when the sketch exists I get a stack trace:
```
java.lang.NullPointerException
    at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:426)
    at quil.applet$destroy_window.invokeStatic(applet.clj:35)
    ...
```

Not entirely surprising, because this sketch is configured to use the PDF renderer and it runs without ever opening a window at all:
```
    (q/sketch
     :size [500 500]
     :renderer :pdf
     :output-file "foo.pdf"
     :setup setup-offscreen
     :settings settings
     :draw draw-offscreen
     :middleware [m/fun-mode])
```
and `draw-offscreen` draws exactly once before exiting:
```
(defn draw-offscreen
  "Generate offscreen rendering context, then render, save, and exit"
  [state]
  (println "draw-offscreen: begin")
  (let [gr (q/current-graphics)]
    (q/with-graphics gr
      (-> state
          update-offscreen
          draw-frame)
      (.dispose gr)))
  (q/exit)
  (println "draw-offscreen: done"))
```

The stack trace refers to this code in applet.clj: 
https://github.com/quil/quil/blob/3.1.0/src/clj/quil/applet.clj#L34-L35

Presumably on line 35 the code attempts to invoke `.getClass` on a null pointer.  If so then a simple fix would be to change the conditional from `if` to `if-let` so that nothing further is done if the pointer is null. e.g.
```
(if-let [native (-> applet .getSurface .getNative)]
    (condp = (.getClass native)
    ; ... etc.
```
This `destroy-window` function seems to exist mainly to handle special cases, and it seems fair to add one more special case to the mix.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
I just ran into this as well. Would it be possible to get a tagged release with the fix?
