### ISSUE TITLE
use with figwheel

### ISSUE THREAD

**Issue by vaibhawc** [quil/quil#330]
So I didn't create project using quil but instead just created using figwheel and included it in :dependencies.
Now when I start with figwheel it is not accepting the name **example** here : 
``(q/defsketch example
    :title "Oh so many grey circles"
    :settings #(q/smooth 2)
    :setup setup
    :draw draw
    :size [323 200])``

I am doing something wrong here. I don't here. Please consider me a newbie to clojure(script).

**Comment by nbeloglazov** [comment]
Have you tried creating project using 
```
lein new quil-cljs example
```
Default template uses figwheel and should work. If it does - you can compare your project that you created manually with the auto-generated one and find the difference.

**Comment by vaibhawc** [comment]
I didn't, I will. Thanks.
