### ISSUE TITLE
Gui with Quil

### ISSUE THREAD

**Issue by Folcon** [quil/quil#341]
I've been wanting to use quil in a way that's controllable with relatively easy to use GUI controls, I've not had a great deal of success embedding the GUI controls within the quil window itself, so I've been looking at seesaw for it. This seems to work in 2d, but I'm wanting to render things in 3d as well if possible.

I've chimed in on an earlier [issue](https://github.com/quil/quil/issues/180#issuecomment-756344319), where I mentioned that I've seen [someone describe attaching an opengl display to a jframe](https://stackoverflow.com/questions/26199534/how-to-attach-opengl-display-to-a-jframe-and-dispose-of-it-properly/28816844#28816844), which is basically what I'm looking to do.

Any advice? If there's a really straightforward to use GUI option in quil that I've missed, I'd be happy to try that instead =)...

**Comment by nbeloglazov** [comment]
There is no straighforward GUI option available for Quil. The issue you found related to using it with seesaw is the best "help" I know. The stackoverflow you mentioned uses lwjgl libray (in partciular [Display.setParent](http://legacy.lwjgl.org/javadoc/org/lwjgl/opengl/Display.html#setParent(java.awt.Canvas))] 

Looked a bit into it just now and I don't know if there is a way to embed p3d quil with seesaw. Looking at Processing codebase - I don't see any way to get opengl-related graphics handle or something that can be embedded in java gui. Processing uses jogamp library. Jogamp has [instructions](https://jogamp.org/wiki/index.php/Using_JOGL_in_AWT_SWT_and_Swing#JOGL_in_Swing) on how to embed opengl in swing. But it requires initializing jogamp in certain way and processing instead always creates full window [code](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PSurfaceJOGL.java#L149-L152). 

Instead processing forums suggest to use special libraries for implementing GUI in processing sketches: [forum](https://forum.processing.org/two/discussion/26881/creating-a-gui-using-processing).

**Comment by Folcon** [comment]
Thanks for the follow-up, I'll try and see if I can figure something out.
