### ISSUE TITLE
Unable to load image

### ISSUE THREAD

**Issue by kannangce** [quil/quil#344]
I tried to load an image as shown in the [load-image example](http://quil.info/sketches/show/snippet_load-image).

The code is as shown below,

```
(ns quil-test.core
  (:require [quil.core :as q :include-macros true]))

(defn setup []
  (let [; create url to load image 100x100
        url "https://placekitten.com/100/100"]
    (q/set-state! :image (q/load-image url))))

(defn draw []
  (let [im (q/state :image)]
    ; check if image is loaded using function loaded?
    (when (q/loaded? im) (q/image im 0 0))))

(q/defsketch my
             :host "host"
             :size [500 500]
             :setup setup
             :draw draw)
```
I tried the code with a lein Clojure project. When I tried to run it, a window just apprears and crashes with the below error. What am I missing?

> /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -XX:-OmitStackTraceInFastThrow -Dclojure.compile.path=/Users/kannanr/Desktop/Kannan/Practice/Clojure-practice/quil-test/target/classes -Dquil-test.version=0.1.0-SNAPSHOT -Dclojure.debug=false "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=51062:/Applications/IntelliJ IDEA.app/Contents/bin" -classpath /Users/kannanr/Desktop/Kannan/Practice/Clojure-practice/quil-test/test:/Users/kannanr/Desktop/Kannan/Practice/Clojure-practice/quil-test/src:/Users/kannanr/Desktop/Kannan/Practice/Clojure-practice/quil-test/dev-resources:/Users/kannanr/Desktop/Kannan/Practice/Clojure-practice/quil-test/resources:/Users/kannanr/Desktop/Kannan/Practice/Clojure-practice/quil-test/target/classes:/Users/kannanr/.m2/repository/org/apache/xmlgraphics/batik-util/1.8/batik-util-1.8.jar:/Users/kannanr/.m2/repository/quil/processing-dxf/3.5.3/processing-dxf-3.5.3.jar:/Users/kannanr/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar:/Users/kannanr/.m2/repository/clojure-complete/clojure-complete/0.2.5/clojure-complete-0.2.5.jar:/Users/kannanr/.m2/repository/quil/processing-svg/3.5.3/processing-svg-3.5.3.jar:/Users/kannanr/.m2/repository/org/apache/xmlgraphics/batik-svggen/1.8/batik-svggen-1.8.jar:/Users/kannanr/.m2/repository/org/apache/xmlgraphics/batik-css/1.8/batik-css-1.8.jar:/Users/kannanr/.m2/repository/org/bouncycastle/bcmail-jdk14/1.38/bcmail-jdk14-1.38.jar:/Users/kannanr/.m2/repository/quil/processing-pdf/3.5.3/processing-pdf-3.5.3.jar:/Users/kannanr/.m2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar:/Users/kannanr/.m2/repository/xalan/xalan/2.7.0/xalan-2.7.0.jar:/Users/kannanr/.m2/repository/bouncycastle/bcprov-jdk14/138/bcprov-jdk14-138.jar:/Users/kannanr/.m2/repository/org/bouncycastle/bctsp-jdk14/1.38/bctsp-jdk14-1.38.jar:/Users/kannanr/.m2/repository/cljsjs/p5/0.9.0-0/p5-0.9.0-0.jar:/Users/kannanr/.m2/repository/bouncycastle/bcmail-jdk14/138/bcmail-jdk14-138.jar:/Users/kannanr/.m2/repository/org/apache/xmlgraphics/batik-dom/1.8/batik-dom-1.8.jar:/Users/kannanr/.m2/repository/org/apache/xmlgraphics/batik-awt-util/1.8/batik-awt-util-1.8.jar:/Users/kannanr/.m2/repository/quil/processing-core/3.5.3/processing-core-3.5.3.jar:/Users/kannanr/.m2/repository/com/lowagie/itext/2.1.7/itext-2.1.7.jar:/Users/kannanr/.m2/repository/quil/gluegen-rt-fat/2.3.2/gluegen-rt-fat-2.3.2.jar:/Users/kannanr/.m2/repository/org/apache/xmlgraphics/batik-ext/1.8/batik-ext-1.8.jar:/Users/kannanr/.m2/repository/xml-apis/xml-apis-ext/1.3.04/xml-apis-ext-1.3.04.jar:/Users/kannanr/.m2/repository/quil/quil/3.1.0/quil-3.1.0.jar:/Users/kannanr/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar:/Users/kannanr/.m2/repository/org/apache/xmlgraphics/batik-xml/1.8/batik-xml-1.8.jar:/Users/kannanr/.m2/repository/org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar:/Users/kannanr/.m2/repository/quil/jogl-all-fat/2.3.2/jogl-all-fat-2.3.2.jar:/Users/kannanr/.m2/repository/org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.jar:/Users/kannanr/.m2/repository/org/bouncycastle/bcprov-jdk14/1.38/bcprov-jdk14-1.38.jar clojure.main -i /private/var/folders/m4/hsz1btvx2bvb3ntd7pnnr3mm0000gn/T/form-init6037852088736543702.clj
> Could not find a method to load https://placekitten.com/100/100
> Syntax error compiling at (/private/var/folders/m4/hsz1btvx2bvb3ntd7pnnr3mm0000gn/T/form-init6037852088736543702.clj:1:125).
> Cannot find anything to run for: quil_test.core
> 
> Full report at:
> /var/folders/m4/hsz1btvx2bvb3ntd7pnnr3mm0000gn/T/clojure-5331289633959966315.edn

I don't find any issue with the code I'm running. What am I missing?

**Comment by jackrusher** [comment]
I think the problem you're seeing here is because there's no file extension on the remote file you're loading, so Processing isn't sure which image format to expect.
