### ISSUE TITLE
Clean-up steps

### ISSUE THREAD

**Issue by rttomlinson** [quil/quil#348]
Is there a concept of "clean-up" after killing a sketch?
I'd like to turn my webcam during on `setup` and capture images in `update` while the sketch is running, but I'm not sure how I'd turn the camera off when the sketch is closed.
I tried looking through some of the docs and for a users' forum. Thanks!

**Comment by nbeloglazov** [comment]
Hi Renzo. Try `:on-close` callback: http://quil.info/api/environment#defsketch

**Comment by rttomlinson** [comment]
Thanks, @nbeloglazov! Still figuring out the docs.
