### ISSUE TITLE
Syntax error (UnsatisfiedLinkError) + Syntax error (NoClassDefFoundError)

### ISSUE THREAD

**Issue by metacortexplus** [quil/quil#350]
Fedora 33
```
➜ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode, sharing)
```

Followed [Installing](https://github.com/quil/quil/wiki/Installing) instructions.
```
➜ lein repl
nREPL server started on port 46307 on host 127.0.0.1 - nrepl://127.0.0.1:46307
REPL-y 0.4.4, nREPL 0.8.3
Clojure 1.10.1
OpenJDK 64-Bit Server VM 11.0.11+9
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use 'helloquil.core :reload-all)
Syntax error (UnsatisfiedLinkError) compiling at (quil/core.cljc:1:1).
Can't load library: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-0.fc33.x86_64/lib/libawt_xawt.so

```

Second run (and repeats):
```
user=> (use 'helloquil.core :reload-all)
Syntax error (NoClassDefFoundError) compiling at (quil/core.cljc:1:1).
Could not initialize class quil.applet__init

```

**Comment by avillega** [comment]
I was facing the same issue. The fix was to use quil version `"4.0.0-SNAPSHOT"` if you want to use Java 11. If you don not need Java 11, quil works better with Java 8.

**Comment by metacortexplus** [comment]
>  use quil version `"4.0.0-SNAPSHOT"`

DId you mean in project.clj?

**Comment by nbeloglazov** [comment]
> DId you mean in project.clj?
Yes.

> Is there convenient way to force quil to use Java 8 (which is also installed, but not used as default)?
I don't think you can do it from quil. But you can try changing which jvm leiningen uses (I'm assuming you running quil using  lein). https://gist.github.com/camsaul/c982019fd915510677236cd4b720a583
