### ISSUE TITLE
liblibgluegen_rt.so.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mmmmillar** [quil/quil#357]
I'm using Quil on Linux and I'm getting the following error if I try to change the renderer to :p3d or :opengl

`/home/matt/code/clojure/second/natives/linux-amd64//libgluegen_rt.so (/home/matt/code/clojure/second/natives/linux-amd64//liblibgluegen_rt.so.so: cannot open shared object file: No such file or directory`

If I used the default renderer it works fine (but cant do 3d)

Java version openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)

Do I need to install other libs? Or install Processing by itself?

**Comment by nbeloglazov** [comment]
Unfortunately it's a known issue I don't know how to resolve. I described it [here](https://github.com/quil/quil/pull/337#issuecomment-877888856). We need someone who understands java class loading well (and maybe even familiar with jogl libraries) to address it. So currently we are blocked on it.

**Comment by dgtized** [comment]
I *believe* this is fixed with the 4.3-SNAPSHOT build so will close this once there is a fixed release. See also #389.

**Comment by dgtized** [comment]
Should be fixed for java17+ with the 4.3.1323 release. Feel free to reopen if it's still an issue.
