### ISSUE TITLE
Cannot stop ESC from closing sketch

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [quil/quil#360]
I'm using Manjaro with i3wm, Quil 3.1.0

The ESC key shuts down the sketch and closes the window immediately upon release.

When using the API example for `raw-key`, pressing down ESC doesn't even set `key-pressed?` to true; the screen remains the same as before pressing and as soon as I release it the sketch closes.

Is this the desired behavior? How can I make ESC behave just like the other keys, i.e. do nothing unless programmed to?

**Comment by benjamin-asdf** [comment]
#417
