### ISSUE TITLE
Merge processing4 and docs?

### ISSUE THREAD

**Issue by lspector** [quil/quil#378]
I understand that some things are broken in the processing4 branch (apparently "it has major issues, like 3D renderer doesn't work: [issue](https://github.com/quil/quil/pull/337)"), but for my own uses and those of my students, this is better than the current master branch, which fails with a mysterious error with Java 9+. 

`4.0.0-SNAPSHOT` works, which is really really great (thank you!!), but nobody would learn this from quil.info or clojars, as far as I can tell, and it's also not obvious from github. The instructions at quil.info say to use `lein new quil` which currently creates a reference to "3.1.0". The "Quil intro" linked on that page actually specifies "2.5.0". I think I only learned about the snapshot working from a discussion that I can't even find now myself. I think most newcomers to Quil will probably just have it fail, without much of a clue why or what to do about it. 

I don't know how decisions about these things are made, but from my perspective it would be great if processing4 were merged into master and all of the docs mentioned above were updated to direct people to the new version. Presumably a note should also be added saying what doesn't work yet.

**Comment by dgtized** [comment]
Take a look at the newly released 4.3-SNAPSHOT, that should have a working 3d renderer and work for Java 17+ on a number of architectures including M1/M2 macos. We are in the process of ensuring it's stable and working correctly, so any additional user testing would be very much appreciated. Some derivative of that build will be the eventual 4.3 release, and we hope to update corresponding documentation and intro docs to match that.

**Comment by dgtized** [comment]
[v4.3.1323](https://github.com/quil/quil/releases/tag/v4.3.1323) has been published to [clojars](https://clojars.org/quil/versions/4.3.1323), and I believe the lein templates reference this version. Give that a shot and see if it works for you. I tried to update quite a number of docs references but I'm sure there are some that were missed so please let me know if anything else needs updating!

**Comment by dgtized** [comment]
Looks like the lein templates are updated but not yet pushed to Clojars, so might be a little bit before that part is updated.
