### ISSUE TITLE
How to run a quil sketch?

### ISSUE THREAD

**Issue by tmcw** [quil/quil#52]
Okay, this is a dumb one, and it clearly reveals my sense of non-lisp-aha-moment-repl-fear

But, the README and accompanying wiki page demonstrate how to run a quil sketch from a `clj` repl, but if a newbie user (mwah) copies and pastes the demo code into `core.clj`, there's no connecting path between the copy-paste-have-file to the see-pretty-stuff-in-screenshot. A one-liner of 'how to run your sketch' would be vital.

This is obviously dumb on my side and is probably better addressed with just insisting people learn clojure concepts first. But, this is a great project to learn clojure concepts by tinkering; it's just hard to find the start button.

**Comment by nbeloglazov** [comment]
Closing this long-standing issue. We have few tutorials of how to run Quil in REPL/LightTable and if there is still problems - please ask in google group: https://groups.google.com/forum/#!forum/clj-processing
