### ISSUE TITLE
fill with hex colors doesn't work

### ISSUE THREAD

**Issue by ericevans0** [quil/quil#71]
Passing hex colors to the fill function doesn't seem to work.
For example,
(fill (color 0 255 0))  ;; shapes fill green
(fill 0x00FF00) ;; shapes don't show against background

Maybe it is a transparency issue. I did try passing in an opaque alpha value, though, and that didn't help.

Also, hex colors work fine with background.
(background 0x00FF00)   ;; makes a green background

Thanks! (And my apologies if I'm just doing something wrong in my call.)

**Comment by floybix** [comment]
Can I suggest Quil use `unchecked-int` rather than `int` given that hex colours are part of the processing API?

**Comment by nbeloglazov** [comment]
Thanks, it does solve the problem! I was wrong and it was quil's fault. Thanks for suggesting `unchecked-int`.
