### ISSUE TITLE
Question: Using processing.video with quil

### ISSUE THREAD

**Issue by phiat** [quil/quil#75]
Can anyone help me out with trying to get the processing.video library working with quil?  I'm trying to port a processing sketch (using video library) to clojure/quil.  I've gone down a few routes and have some milestones of success getting the video classes and handling processing 2.0 stuff... But I still can't get it working.  I've been digging deeper and deeper into this and will try to ask here for further help.

 Any suggestions welcome!

**Comment by minikomi** [comment]
There's a much easier way to do this for people who want to get started without having to patch quil:

1. Download processing, and move Processing.app/Contents/Java/modes/java/libraries/video/library/ into your project.
2. Add the following resource paths into your project.clj:

```clj
  :resource-paths [
                   "library/jna.jar"
                   "library/video.jar"
                   "library/gstreamer-java.jar"
                   "library/gstreamer/macosx64"
                   ]

```
3. Use code like the following:

```clj
(ns videotest.core
  (:require [quil.core :as q]
            [quil.middleware :as m]
            )
  (:import [processing.video Movie]))

(defn setup []
  (let [mov (Movie. (quil.applet/current-applet) "resources/720.mp4")]
    (.play mov)
    (.loop mov)
    {:movie mov
     :current-frame 0}))

(defn update-state [state]
  (when (and (not (nil? (:movie state)))
                (.available (:movie state)))
    (.read (:movie state)))
  state)

(defn draw-state [state]
  (q/background 240)
  (q/image (:movie state) 0 0))

(q/defsketch videotest
  :size [1280 720]
  :setup setup
  :update update-state
  :draw draw-state
  :features [:keep-on-top]
  :middleware [m/fun-mode])
```

Note the use of `(.available (:movie state))`  to see if it's safe to read a new frame.

**Comment by Norgat** [comment]
Little trick.

```Clojure
:resource-paths [
                   "library/jna.jar"
                   "library/video.jar"
                   "library/gstreamer-java.jar"
                   "library/gstreamer/macosx64"
                   ]
```

You can use this plugin for adding (and more other things) jars to local maven repo: https://github.com/kumarshantanu/lein-localrepo

**Comment by bmaddy** [comment]
Those `.jar` files from @minikomi's comment seem to not exist in `Processing.app/Contents/Java/modes/java/libraries/video/library/ ` anymore. Does anyone know where I could find them? I'm also trying to get this to work.

**Comment by hamoid** [comment]
@bmaddy In Processing, go to Preferences and note your sketchbook folder. I think you should find the files you are looking for inside ```[sketchbook folder]/libraries/video/library```

**Comment by tripaces** [comment]
Pulling together several elements from this thread and others, I put together a sketch using a webcam and Raspberry Pi 2 using the newer Processing video libraries (as pointed out by @hamoid).

That sketch, which is inspired by one of the Processing Video Capture examples is at https://github.com/LifeInLights/twyla-opus/blob/master/spectacles/src/spectacles/mirror_camera.clj and is quite reliable.

The associated project (https://github.com/LifeInLights/twyla-opus/blob/master/spectacles/project.clj) indicates how to reference the necessary jars. Since the time of writing, it is possible that those libraries may have been made available in a public repo, but at the time they had to be directly embedded for reliable availability (https://github.com/LifeInLights/twyla-opus/tree/master/spectacles/resources/processing-video).

**Comment by minikomi** [comment]
The easiest way I found was to download processing, start a new sketch, select add library from the sketch menu and then do a search for video. The one you want is the gstreamer libary called "video". Now, in your Documents folder should be a Processing/libraries folder with the video plugin there.

**Comment by nbeloglazov** [comment]
Took a look at processing.video. I think a jar to clojars is pretty straightforward. The hard part is how to serve libraries (non-java libraries). In my Processing/libraries/video folder I see 97mb of libraries for Windows and MacOS. Uploading them to clojars doesn't seem like a good solution. Ideally there should be something like a script that downloads them to your computer when you "enable" video for quil. If lein had something like post-dependency-included-hook that would do it. But I don't know how to do it.

**Comment by nbeloglazov** [comment]
Going to close this bug. There is a FAQ entry to using processing plugins with Quil: https://github.com/quil/quil/wiki/FAQ#how-to-use-processing-plugin and according @minikomi that will work.
