### ISSUE TITLE
Move to clojure 1.6

### ISSUE THREAD

**Issue by nbeloglazov** [quil/quil#88]
Move to clojure 1.6.
Create profile in `project.clj` which will run all snippets in clojure 1.6 and 1.5.1.

**Comment by bsima** [comment]
+1 now that Clojure 1.7 is out. What exactly is preventing this from moving forward? The comment above just mentions AOT compilation but I don't understand why that won't work in 1.6 or 1.7.

**Comment by nbeloglazov** [comment]
It will work in 1.6 and 1.7, but will fail on 1.5. I agree that we can probably drop support of 1.5 now.

I'd love to migrate to 1.7 and start using reader conditionals instead of cljx, but I don't think it is feasible now as it means breaking 1.6.
